import { equalityFractionNotation } from './equality-notation';
export const TRANSFER_ROUNDS = [
  {
    equation: 'x + 5 = 12',
    term: '+5',
    right: '12',
    magnitude: '5',
    sign: '−',
    operation: 'Trừ 5 ở cả hai vế',
    expanded: 'x + 5 - 5 = 12 - 5',
    simplified: 'x = 12 - 5',
    choices: ['17', '7', '-7'],
    answer: '7',
    working: '12 - 5 = 7',
    check: '7 + 5 = 12',
    hint: 'Chuyển số hạng +5 sang vế phải thành -5. Tính 12 - 5.',
  },
  {
    equation: 'x - 2/3 = -1/4',
    term: '-2/3',
    right: '-1/4',
    magnitude: '2/3',
    sign: '+',
    operation: 'Cộng 2/3 ở cả hai vế',
    expanded: 'x - 2/3 + 2/3 = -1/4 + 2/3',
    simplified: 'x = -1/4 + 2/3',
    choices: ['-11/12', '11/12', '5/12'],
    answer: '5/12',
    working: '-1/4 + 2/3 = -3/12 + 8/12 = 5/12',
    check: '5/12 - 2/3 = 5/12 - 8/12 = -3/12 = -1/4',
    hint: 'Giữ dấu âm của -1/4: -1/4 = -3/12 và 2/3 = 8/12. Cộng hai tử -3 và 8, giữ mẫu 12.',
  },
] as const;

export function balanceState(left: number, right: number) {
  return {
    equal: left === right,
    complete: left === 5 && right === 5,
    relation: left === right ? '=' : left < right ? '<' : '>',
    // SVG's y axis points down, so the heavier pan must move down.
    tilt: left === right ? 0 : left > right ? -8 : 8,
  };
}

// Each activity asks for a transformation before revealing the calculation.
const originalOPERATION_ROUNDS = [
  {
    title: 'Phép nhân: tìm thừa số chưa biết',
    equation: '3x = 12',
    prompt: 'Làm gì ở cả hai vế để x đứng một mình?',
    options: ['Chia cho 3', 'Trừ 3', 'Nhân với 3'],
    operation: 'Chia cho 3',
    explanation: '3 đang nhân với x. Chia cả hai vế cho 3: 3x : 3 = 12 : 3.',
    working: 'x = 12 : 3',
    choices: ['9', '4', '36'],
    answer: '4',
    hint: 'Tính 12 : 3, không phải 12 - 3.',
    check: '3 × 4 = 12.',
  },
  {
    title: 'Phép chia: tìm số bị chia',
    equation: 'x : 4 = -2',
    prompt: 'Chọn phép biến đổi để bỏ phép chia cho 4.',
    options: [
      'Chia cả hai vế cho 4',
      'Nhân cả hai vế với 4',
      'Cộng 4 vào hai vế',
    ],
    operation: 'Nhân cả hai vế với 4',
    explanation: 'Nhân cả hai vế với 4: (x : 4) × 4 = -2 × 4.',
    working: 'x = -2 × 4',
    choices: ['-8', '-1/2', '2'],
    answer: '-8',
    hint: 'Một số âm nhân với một số dương cho kết quả âm.',
    check: '-8 : 4 = -2.',
  },
  {
    title: 'Phép chia: x là số chia',
    equation: '12 : x = 3',
    prompt: 'Biết x ≠ 0. Nhân cả hai vế với x, ta được dòng nào?',
    options: ['12 = 3x', 'x = 3 : 12', '12 - x = 3'],
    operation: '12 = 3x',
    explanation:
      'Vì x ≠ 0, nhân hai vế với x được 12 = 3x. Sau đó chia hai vế cho 3.',
    working: 'x = 12 : 3',
    choices: ['1/4', '4', '0'],
    answer: '4',
    hint: 'Tìm số chia bằng số bị chia chia cho thương. x không được bằng 0.',
    check: '12 : 4 = 3; 4 ≠ 0.',
  },
  {
    title: 'Phân số: chia cho một phân số',
    equation: '(1/2) × x = 3/4',
    prompt: 'Chọn phép biến đổi để tìm x.',
    options: ['x = 3/4 - 1/2', 'x = (3/4) : (1/2)', 'x = (3/4) × (1/2)'],
    operation: 'x = (3/4) : (1/2)',
    explanation:
      'Chia cả hai vế cho 1/2. Chia cho 1/2 là nhân với số nghịch đảo 2.',
    working: 'x = (3/4) × 2',
    choices: ['3/8', '1/4', '3/2'],
    answer: '3/2',
    hint: 'Nhân tử số với 2 rồi rút gọn: (3 × 2)/4.',
    check: '(1/2) × (3/2) = 3/4.',
  },
  {
    title: 'Lũy thừa đã biết: tính trước',
    equation: 'x + 2^3 = 11',
    prompt: 'Tính lũy thừa trước. Dòng nào đúng?',
    options: ['x + 6 = 11', 'x + 8 = 11', 'x = 11 : 8'],
    operation: 'x + 8 = 11',
    explanation:
      '2^3 = 2 × 2 × 2 = 8. Sau đó chuyển số hạng +8 sang vế phải thành -8.',
    working: 'x = 11 - 8',
    choices: ['3', '5', '19'],
    answer: '3',
    hint: 'Số mũ 3 cho biết có ba thừa số 2; không phải 2 × 3.',
    check: '3 + 2^3 = 3 + 8 = 11.',
  },
  {
    title: 'x ở số mũ: đưa về cùng cơ số',
    equation: '2^(x + 1) = 32',
    prompt: 'Với x ∈ ℕ, viết 32 thành lũy thừa của 2. Ta được điều gì?',
    options: ['x + 1 = 5', 'x + 1 = 16', 'x = 32 - 2'],
    operation: 'x + 1 = 5',
    explanation:
      '32 = 2^5. Với các số mũ tự nhiên, hai lũy thừa cơ số 2 bằng nhau khi số mũ bằng nhau: x + 1 = 5.',
    working: 'x = 5 - 1',
    choices: ['5', '4', '6'],
    answer: '4',
    hint: 'Đã tìm được x + 1 = 5. Cần trừ tiếp 1 để tìm x.',
    check: '2^(4 + 1) = 2^5 = 32; 4 ∈ ℕ.',
  },
  {
    title: 'Nhân lũy thừa cùng cơ số: cộng số mũ',
    equation: '2^x × 2^3 = 2^7',
    prompt: 'Với x ∈ ℕ, gộp hai lũy thừa ở vế trái. Dòng nào đúng?',
    options: ['2^(3x) = 2^7', '2^(x + 3) = 2^7', '4^(x + 3) = 2^7'],
    operation: '2^(x + 3) = 2^7',
    explanation:
      'Nhân hai lũy thừa cùng cơ số: giữ cơ số, cộng số mũ. Vì vậy 2^x × 2^3 = 2^(x + 3). Hai lũy thừa cơ số 2 bằng nhau nên x + 3 = 7.',
    working: 'x = 7 - 3',
    choices: ['10', '4', '7/3'],
    answer: '4',
    hint: 'Từ x + 3 = 7, chuyển +3 sang vế phải thành -3: x = 7 - 3.',
    check: '2^4 × 2^3 = 2^(4 + 3) = 2^7; 4 ∈ ℕ.',
  },
  {
    title: 'Chia lũy thừa cùng cơ số: trừ số mũ',
    equation: '2^x : 2^3 = 2^4',
    prompt: 'Với x ∈ ℕ, x ≥ 3, gộp hai lũy thừa ở vế trái. Dòng nào đúng?',
    options: ['2^(x + 3) = 2^4', '2^(x : 3) = 2^4', '2^(x - 3) = 2^4'],
    operation: '2^(x - 3) = 2^4',
    explanation:
      'Chia hai lũy thừa cùng cơ số khác 0: giữ cơ số, lấy số mũ của số bị chia trừ số mũ của số chia. Vì vậy 2^x : 2^3 = 2^(x - 3). Hai lũy thừa cơ số 2 bằng nhau nên x - 3 = 4.',
    working: 'x = 4 + 3',
    choices: ['1', '7', '12'],
    answer: '7',
    hint: 'Từ x - 3 = 4, chuyển -3 sang vế phải thành +3: x = 4 + 3.',
    check: '2^7 : 2^3 = 2^(7 - 3) = 2^4; 7 ∈ ℕ và 7 ≥ 3.',
  },
  {
    title: 'Tìm x qua hai bước: chuyển vế rồi chia',
    equation: '2x + 3 = 11',
    prompt: 'Trước hết, chuyển số hạng +3 sang vế phải. Dòng nào đúng?',
    options: ['2x = 11 + 3', '2x = 11 - 3', 'x = 11 - 3'],
    operation: '2x = 11 - 3',
    explanation:
      'Chuyển +3 sang vế phải thành -3: 2x = 11 - 3 = 8. Số 2 đang nhân với x, nên tiếp theo chia cả hai vế cho 2.',
    working: 'x = 8 : 2',
    choices: ['8', '4', '6'],
    answer: '4',
    hint: 'Sau khi chuyển vế, ta mới tìm được 2x = 8. Cần chia tiếp cho 2 để tìm x.',
    check: '2 × 4 + 3 = 8 + 3 = 11. Hai vế bằng nhau.',
  },
  {
    title: 'Tìm x trong ngoặc: chia trước, chuyển vế sau',
    equation: '3 × (x + 2) = 15',
    prompt: 'Chia cả hai vế cho 3 để tìm giá trị trong ngoặc. Dòng nào đúng?',
    options: ['x + 2 = 15 - 3', 'x = 15 : 3', 'x + 2 = 15 : 3'],
    operation: 'x + 2 = 15 : 3',
    explanation:
      'Cả biểu thức x + 2 đang nhân với 3. Chia hai vế cho 3 được x + 2 = 5. Sau đó chuyển +2 sang vế phải thành -2.',
    working: 'x = 5 - 2',
    choices: ['5', '3', '7'],
    answer: '3',
    hint: '5 là giá trị của x + 2. Trừ tiếp 2 để tìm x.',
    check: '3 × (3 + 2) = 3 × 5 = 15. Hai vế bằng nhau.',
  },
  {
    title: 'Tìm x khi đứng sau dấu trừ',
    equation: '5 - x = 8',
    prompt: 'Chuyển số hạng +5 sang vế phải. Dòng nào đúng?',
    options: ['x = 8 - 5', '-x = 8 - 5', '-x = 8 + 5'],
    operation: '-x = 8 - 5',
    explanation:
      'Trừ 5 ở cả hai vế được -x = 3. Nhân cả hai vế với -1 để tìm x.',
    working: 'x = -3',
    choices: ['3', '-3', '13'],
    answer: '-3',
    hint: '-x = 3 nghĩa là số đối của x bằng 3, nên x = -3.',
    check: '5 - (-3) = 5 + 3 = 8.',
  },
  {
    title: 'Chia cho hệ số âm',
    equation: '-2x = 6',
    prompt: 'Chọn phép biến đổi để x đứng một mình.',
    options: ['x = 6 + 2', 'x = 6 : 2', 'x = 6 : (-2)'],
    operation: 'x = 6 : (-2)',
    explanation:
      '-2 đang nhân với x. Chia cả hai vế cho -2; số dương chia số âm cho kết quả âm.',
    working: 'x = 6 : (-2)',
    choices: ['3', '-3', '8'],
    answer: '-3',
    hint: 'Giữ dấu âm của hệ số khi chia: 6 : (-2) = -3.',
    check: '(-2) × (-3) = 6.',
  },
  {
    title: 'Dấu trừ trước ngoặc',
    equation: '10 - (x + 2) = 3',
    prompt: 'Bỏ ngoặc sau dấu trừ. Dòng nào đúng?',
    options: ['10 - x + 2 = 3', '10 - x - 2 = 3', '10 + x - 2 = 3'],
    operation: '10 - x - 2 = 3',
    explanation:
      'Dấu trừ trước ngoặc đổi dấu từng số hạng trong ngoặc: -(x + 2) = -x - 2. Thu gọn được 8 - x = 3, nên -x = -5.',
    working: 'x = 8 - 3',
    choices: ['9', '-5', '5'],
    answer: '5',
    hint: 'Cả x và +2 đều đổi dấu khi bỏ ngoặc. Từ -x = -5, nhân hai vế với -1.',
    check: '10 - (5 + 2) = 10 - 7 = 3.',
  },
];
export const OPERATION_ROUNDS = originalOPERATION_ROUNDS.map((round) => ({
  ...round,
  options: round.options.map(equalityFractionNotation),
  operation: equalityFractionNotation(round.operation),
  explanation: equalityFractionNotation(round.explanation),
  working: equalityFractionNotation(round.working),
  hint: equalityFractionNotation(round.hint),
}));
export const EQUALITY_ROUND_COUNT =
  1 + TRANSFER_ROUNDS.length + OPERATION_ROUNDS.length;
