import { MathLessonData } from './lessons';

export const fractionLessons: MathLessonData[] = [
  {
    "id": "math-fraction-basics-6",
    "title": "Mở rộng phân số: số nguyên, tính chất và rút gọn",
    "grade": 6,
    "topic": "Phân số mở rộng",
    "goal": "Ôn kiến thức phân số tiểu học. Nhận biết tử, mẫu; viết phân số bằng nhau và rút gọn. Mở rộng với phân số có tử hoặc mẫu là số nguyên âm.",
    "textbook": "Bài tự biên soạn theo chủ đề Phân số lớp 6; không gắn với trang hay ấn bản sách cụ thể.",
    "teacherNotes": "Học sau Số nguyên và Tính chia hết. Phân số đã được học từ lớp 4; lớp 6 mở rộng sang tử, mẫu là số nguyên và bài toán tìm số ban đầu. Các câu cơ bản dùng để ôn tập.",
    "knowledgeSummary": "Khái niệm: Phân số có dạng a/b với a, b là số nguyên và b khác 0. a là tử số, b là mẫu số. Mỗi số nguyên n có thể viết thành n/1.\nPhân số bằng nhau: a/b = c/d khi a × d = b × c (b, d khác 0). Nhân cả tử và mẫu với cùng một số nguyên khác 0 thì được phân số bằng phân số đã cho.\nRút gọn: Chia cả tử và mẫu cho cùng một ước chung khác 0. Phân số tối giản có tử và mẫu không còn ước chung lớn hơn 1. Thường viết mẫu số lớn hơn 0.\nVí dụ: -2/3 = (-2 × 4)/(3 × 4) = -8/12.\nLưu ý: Mẫu số phải khác 0; rút gọn kết quả.",
    "blocks": [
      {
        "id": "math-fraction-basics-6-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ở tiểu học, em đã học phân số với tử là số tự nhiên, mẫu là số tự nhiên khác 0. Bài này ôn lại kiến thức đó rồi mở rộng. Ôn phép tính với số nguyên; có thể dùng ƯCLN để rút gọn và BCNN để quy đồng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-k0",
        "section": "explore",
        "title": "Khái niệm",
        "text": "Ở lớp 6, phân số được mở rộng: a/b với a, b là số nguyên và b khác 0. Tử hoặc mẫu có thể là số nguyên âm, ví dụ -3/5 và 3/(-5). Mỗi số nguyên n viết được thành n/1.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-k1",
        "section": "explore",
        "title": "Phân số bằng nhau",
        "text": "a/b = c/d khi a × d = b × c (b, d khác 0). Nhân cả tử và mẫu với cùng một số nguyên khác 0 thì được phân số bằng phân số đã cho.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-k2",
        "section": "explore",
        "title": "Rút gọn",
        "text": "Chia cả tử và mẫu cho cùng một ước chung khác 0. Phân số tối giản có tử và mẫu không còn ước chung lớn hơn 1. Thường viết mẫu số lớn hơn 0.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-ex0",
        "section": "example",
        "title": "1. Tính chất cơ bản",
        "text": "-2/3 = (-2 × 4)/(3 × 4) = -8/12.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-ex1",
        "section": "example",
        "title": "2. Rút gọn từng bước",
        "text": "-18/24 = (-18 : 6)/(24 : 6) = -3/4. ƯCLN(18, 24) = 6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-basics-6-guide",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Nhận biết tử, mẫu; viết phân số bằng nhau và rút gọn.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Cách viết nào là phân số?",
        "answer": "-3/5",
        "hint": "Tử và mẫu là số nguyên, mẫu khác 0.",
        "solution": "-3 và 5 là số nguyên; 5 khác 0.",
        "options": [
          "-3/5",
          "3/0",
          "(1,5)/2"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q1",
        "section": "foundation",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Rút gọn 6/8.",
        "answer": "3/4",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "6/8 = (6 : 2)/(8 : 2) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q2",
        "section": "guided",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Rút gọn -14/49.",
        "answer": "-2/7",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "-14/49 = (-14 : 7)/(49 : 7) = -2/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm x: 4/9 = x/45.",
        "answer": "20",
        "hint": "45 = 9 × 5.",
        "solution": "x = 4 × 5 = 20.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Cách viết nào là phân số?",
        "answer": "-3/5",
        "hint": "Tử và mẫu là số nguyên, mẫu khác 0.",
        "solution": "-3 và 5 là số nguyên; 5 khác 0.",
        "options": [
          "-3/5",
          "3/0",
          "(1,5)/2"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q5",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tử số của phân số -7/9 là bao nhiêu?",
        "answer": "-7",
        "hint": "Tử số ở trên gạch phân số.",
        "solution": "Tử số là -7.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q6",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Mẫu số của phân số -7/9 là bao nhiêu?",
        "answer": "9",
        "hint": "Mẫu số ở dưới gạch phân số.",
        "solution": "Mẫu số là 9.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q7",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Phân số nào bằng 2/3?",
        "answer": "6/9",
        "hint": "Nhân cả tử và mẫu với cùng một số khác 0.",
        "solution": "2/3 = (2 × 3)/(3 × 3) = 6/9.",
        "options": [
          "6/9",
          "4/9",
          "2/9"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q8",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 6/8.",
        "answer": "3/4",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "6/8 = (6 : 2)/(8 : 2) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q9",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn -9/12.",
        "answer": "-3/4",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "-9/12 = (-9 : 3)/(12 : 3) = -3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q10",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 15/25.",
        "answer": "3/5",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "15/25 = (15 : 5)/(25 : 5) = 3/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q11",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 18/24.",
        "answer": "3/4",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "18/24 = (18 : 6)/(24 : 6) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q12",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 21/35.",
        "answer": "3/5",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "21/35 = (21 : 7)/(35 : 7) = 3/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn -14/49.",
        "answer": "-2/7",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "-14/49 = (-14 : 7)/(49 : 7) = -2/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q14",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 36/48.",
        "answer": "3/4",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "36/48 = (36 : 12)/(48 : 12) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q15",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 0/7.",
        "answer": "0",
        "hint": "Chia cả tử và mẫu cho ƯCLN của chúng.",
        "solution": "0/7 = (0 : 7)/(7 : 7) = 0.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q16",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: 2/5 = x/15.",
        "answer": "6",
        "hint": "15 = 5 × 3.",
        "solution": "x = 2 × 3 = 6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: -3/7 = x/14.",
        "answer": "-6",
        "hint": "14 = 7 × 2.",
        "solution": "x = -3 × 2 = -6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: 4/9 = x/45.",
        "answer": "20",
        "hint": "45 = 9 × 5.",
        "solution": "x = 4 × 5 = 20.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Phân số nào tối giản?",
        "answer": "5/12",
        "hint": "Tử và mẫu không có ước chung lớn hơn 1.",
        "solution": "ƯCLN(5, 12) = 1 nên 5/12 tối giản.",
        "options": [
          "5/12",
          "6/9",
          "8/12"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Viết 3/(-4) với mẫu số lớn hơn 0.",
        "answer": "-3/4",
        "hint": "Đổi dấu cả tử và mẫu.",
        "solution": "3/(-4) = -3/4.",
        "options": [
          "-3/4",
          "3/4",
          "-4/3"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q21",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một hình chia thành 12 phần bằng nhau, tô màu 8 phần. Phần tô màu chiếm bao nhiêu phần của hình?",
        "answer": "2/3",
        "hint": "Viết phân số rồi rút gọn.",
        "solution": "8/12 = (8 : 4)/(12 : 4) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-basics-6-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Khẳng định nào đúng?",
        "answer": "-2/3 = 2/(-3)",
        "hint": "Đổi dấu cả tử và mẫu không đổi giá trị phân số.",
        "solution": "2/(-3) = -2/3.",
        "options": [
          "-2/3 = 2/(-3)",
          "-2/3 = 2/3",
          "-2/3 = -3/2"
        ],
        "kind": "choice",
        "id": "math-fraction-basics-6-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: x/18 = -5/6.",
        "answer": "-15",
        "hint": "18 = 6 × 3.",
        "solution": "x = -5 × 3 = -15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-basics-6-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phân số: khái niệm, tính chất và rút gọn",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-compare-6",
    "title": "Quy đồng và so sánh phân số có số âm",
    "grade": 6,
    "topic": "Phân số mở rộng",
    "goal": "Ôn kiến thức phân số tiểu học. Quy đồng về mẫu lớn hơn 0 và so sánh các phân số. Mở rộng với phân số có tử hoặc mẫu là số nguyên âm.",
    "textbook": "Bài tự biên soạn theo chủ đề Phân số lớp 6; không gắn với trang hay ấn bản sách cụ thể.",
    "teacherNotes": "Học sau Số nguyên và Tính chia hết. Phân số đã được học từ lớp 4; lớp 6 mở rộng sang tử, mẫu là số nguyên và bài toán tìm số ban đầu. Các câu cơ bản dùng để ôn tập.",
    "knowledgeSummary": "Quy đồng mẫu số: Viết các phân số với mẫu lớn hơn 0. Chọn mẫu chung (thường là BCNN các mẫu), tìm thừa số phụ rồi nhân cả tử và mẫu với thừa số phụ tương ứng.\nSo sánh: Hai phân số cùng mẫu lớn hơn 0: phân số có tử lớn hơn thì lớn hơn. Khác mẫu: quy đồng rồi so sánh. Phân số âm nhỏ hơn 0, phân số dương lớn hơn 0.\nVí dụ: So sánh 3/4 và 5/6. BCNN(4, 6) = 12.\n3/4 = (3 × 3)/(4 × 3) = 9/12; 5/6 = (5 × 2)/(6 × 2) = 10/12.\nLưu ý: Mẫu số phải khác 0; rút gọn kết quả.",
    "blocks": [
      {
        "id": "math-fraction-compare-6-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ở tiểu học, em đã học phân số với tử là số tự nhiên, mẫu là số tự nhiên khác 0. Bài này ôn lại kiến thức đó rồi mở rộng. Ôn phép tính với số nguyên; có thể dùng ƯCLN để rút gọn và BCNN để quy đồng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-6-k0",
        "section": "explore",
        "title": "Quy đồng mẫu số",
        "text": "Viết các phân số với mẫu lớn hơn 0. Chọn mẫu chung (thường là BCNN các mẫu), tìm thừa số phụ rồi nhân cả tử và mẫu với thừa số phụ tương ứng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-6-k1",
        "section": "explore",
        "title": "So sánh",
        "text": "Hai phân số cùng mẫu lớn hơn 0: phân số có tử lớn hơn thì lớn hơn. Khác mẫu: quy đồng rồi so sánh. Phân số âm nhỏ hơn 0, phân số dương lớn hơn 0.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-6-ex0",
        "section": "example",
        "title": "1. Quy đồng",
        "text": "So sánh 3/4 và 5/6. BCNN(4, 6) = 12.\n3/4 = (3 × 3)/(4 × 3) = 9/12; 5/6 = (5 × 2)/(6 × 2) = 10/12.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-6-ex1",
        "section": "example",
        "title": "2. So sánh tử",
        "text": "9 < 10 nên 9/12 < 10/12. Vậy 3/4 < 5/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-6-guide",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Quy đồng về mẫu lớn hơn 0 và so sánh các phân số.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/4 và 1/6.",
        "answer": "12",
        "hint": "Tìm BCNN của hai mẫu.",
        "solution": "BCNN(4, 6) = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q1",
        "section": "foundation",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "So sánh 1/3 và 1/2.",
        "answer": "1/3 < 1/2",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "1/3 = 2/6; 1/2 = 3/6. Vì 2 < 3 nên 1/3 < 1/2.",
        "options": [
          "1/3 < 1/2",
          "1/3 > 1/2",
          "1/3 = 1/2"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q2",
        "section": "guided",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "So sánh 2/3 và 4/6.",
        "answer": "2/3 = 4/6",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "2/3 = 4/6; 4/6 = 4/6. Vì 4 = 4 nên 2/3 = 4/6.",
        "options": [
          "2/3 < 4/6",
          "2/3 > 4/6",
          "2/3 = 4/6"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q3",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Quy đồng 5/6 về mẫu 18. Tử số mới là bao nhiêu?",
        "answer": "15",
        "hint": "Nhân cả tử và mẫu với thừa số phụ.",
        "solution": "5/6 = (5 × 3)/(6 × 3) = 15/18.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/4 và 1/6.",
        "answer": "12",
        "hint": "Tìm BCNN của hai mẫu.",
        "solution": "BCNN(4, 6) = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q5",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/6 và 1/8.",
        "answer": "24",
        "hint": "Tìm BCNN của hai mẫu.",
        "solution": "BCNN(6, 8) = 24.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q6",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/9 và 1/12.",
        "answer": "36",
        "hint": "Tìm BCNN của hai mẫu.",
        "solution": "BCNN(9, 12) = 36.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q7",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/10 và 1/15.",
        "answer": "30",
        "hint": "Tìm BCNN của hai mẫu.",
        "solution": "BCNN(10, 15) = 30.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q8",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 1/3 và 1/2.",
        "answer": "1/3 < 1/2",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "1/3 = 2/6; 1/2 = 3/6. Vì 2 < 3 nên 1/3 < 1/2.",
        "options": [
          "1/3 < 1/2",
          "1/3 > 1/2",
          "1/3 = 1/2"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q9",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 3/5 và 2/5.",
        "answer": "3/5 > 2/5",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "3/5 = 3/5; 2/5 = 2/5. Vì 3 > 2 nên 3/5 > 2/5.",
        "options": [
          "3/5 < 2/5",
          "3/5 > 2/5",
          "3/5 = 2/5"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q10",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh -2/7 và 1/7.",
        "answer": "-2/7 < 1/7",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "-2/7 = -2/7; 1/7 = 1/7. Vì -2 < 1 nên -2/7 < 1/7.",
        "options": [
          "-2/7 < 1/7",
          "-2/7 > 1/7",
          "-2/7 = 1/7"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q11",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh -3/4 và -2/3.",
        "answer": "-3/4 < -2/3",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "-3/4 = -9/12; -2/3 = -8/12. Vì -9 < -8 nên -3/4 < -2/3.",
        "options": [
          "-3/4 < -2/3",
          "-3/4 > -2/3",
          "-3/4 = -2/3"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q12",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 5/6 và 7/9.",
        "answer": "5/6 > 7/9",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "5/6 = 15/18; 7/9 = 14/18. Vì 15 > 14 nên 5/6 > 7/9.",
        "options": [
          "5/6 < 7/9",
          "5/6 > 7/9",
          "5/6 = 7/9"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q13",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 2/3 và 4/6.",
        "answer": "2/3 = 4/6",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "2/3 = 4/6; 4/6 = 4/6. Vì 4 = 4 nên 2/3 = 4/6.",
        "options": [
          "2/3 < 4/6",
          "2/3 > 4/6",
          "2/3 = 4/6"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q14",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh -1/2 và -3/8.",
        "answer": "-1/2 < -3/8",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "-1/2 = -4/8; -3/8 = -3/8. Vì -4 < -3 nên -1/2 < -3/8.",
        "options": [
          "-1/2 < -3/8",
          "-1/2 > -3/8",
          "-1/2 = -3/8"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q15",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 7/8 và 5/6.",
        "answer": "7/8 > 5/6",
        "hint": "Quy đồng mẫu số rồi so sánh tử số.",
        "solution": "7/8 = 21/24; 5/6 = 20/24. Vì 21 > 20 nên 7/8 > 5/6.",
        "options": [
          "7/8 < 5/6",
          "7/8 > 5/6",
          "7/8 = 5/6"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q16",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 2/3 về mẫu 12. Tử số mới là bao nhiêu?",
        "answer": "8",
        "hint": "Nhân cả tử và mẫu với thừa số phụ.",
        "solution": "2/3 = (2 × 4)/(3 × 4) = 8/12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng -3/5 về mẫu 20. Tử số mới là bao nhiêu?",
        "answer": "-12",
        "hint": "Nhân cả tử và mẫu với thừa số phụ.",
        "solution": "-3/5 = (-3 × 4)/(5 × 4) = -12/20.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 5/6 về mẫu 18. Tử số mới là bao nhiêu?",
        "answer": "15",
        "hint": "Nhân cả tử và mẫu với thừa số phụ.",
        "solution": "5/6 = (5 × 3)/(6 × 3) = 15/18.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng -2/7 về mẫu 21. Tử số mới là bao nhiêu?",
        "answer": "-6",
        "hint": "Nhân cả tử và mẫu với thừa số phụ.",
        "solution": "-2/7 = (-2 × 3)/(7 × 3) = -6/21.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Lan đọc 3/4 quyển sách, Mai đọc 5/8 cùng quyển sách đó. Ai đọc nhiều hơn?",
        "answer": "Lan",
        "hint": "Đưa về mẫu 8.",
        "solution": "3/4 = 6/8 > 5/8 nên Lan đọc nhiều hơn.",
        "options": [
          "Lan",
          "Mai",
          "Hai bạn bằng nhau"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q21",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Sắp xếp theo thứ tự tăng dần.",
        "answer": "-1/2 < 1/3 < 2/3",
        "hint": "Số âm nhỏ hơn số dương.",
        "solution": "-1/2 < 0 < 1/3 < 2/3.",
        "options": [
          "-1/2 < 1/3 < 2/3",
          "1/3 < -1/2 < 2/3",
          "2/3 < 1/3 < -1/2"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-6-q22",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm số nguyên x: 2/5 < x/5 < 4/5.",
        "answer": "3",
        "hint": "Các phân số cùng mẫu 5.",
        "solution": "2 < x < 4 nên x = 3.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm mẫu chung nhỏ nhất của 1/6, 1/8 và 1/12.",
        "answer": "24",
        "hint": "Tìm BCNN của cả ba mẫu.",
        "solution": "6 = 2 × 3; 8 = 2³; 12 = 2² × 3. BCNN(6, 8, 12) = 24.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-6-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phân số: quy đồng và so sánh",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-subtract-6",
    "title": "Phép trừ phân số và số đối",
    "grade": 6,
    "topic": "Phân số mở rộng",
    "goal": "Ôn kiến thức phân số tiểu học. Tìm số đối, trừ phân số và tìm thành phần chưa biết. Mở rộng với phân số có tử hoặc mẫu là số nguyên âm.",
    "textbook": "Bài tự biên soạn theo chủ đề Phân số lớp 6; không gắn với trang hay ấn bản sách cụ thể.",
    "teacherNotes": "Học sau Số nguyên và Tính chia hết. Phân số đã được học từ lớp 4; lớp 6 mở rộng sang tử, mẫu là số nguyên và bài toán tìm số ban đầu. Các câu cơ bản dùng để ôn tập.",
    "knowledgeSummary": "Số đối: Hai số có tổng bằng 0 là hai số đối nhau. Số đối của 2/3 là -2/3; số đối của 0 là 0.\nPhép trừ: Muốn trừ một phân số cho một phân số, ta cộng số bị trừ với số đối của số trừ. Cùng mẫu: trừ tử và giữ mẫu. Khác mẫu: quy đồng trước. Rút gọn kết quả.\nVí dụ: 5/6 − 1/4 = 10/12 − 3/12 = (10 − 3)/12 = 7/12.\nLưu ý: Mẫu số phải khác 0; rút gọn kết quả.",
    "blocks": [
      {
        "id": "math-fraction-subtract-6-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ở tiểu học, em đã học phân số với tử là số tự nhiên, mẫu là số tự nhiên khác 0. Bài này ôn lại kiến thức đó rồi mở rộng. Ôn phép tính với số nguyên; có thể dùng ƯCLN để rút gọn và BCNN để quy đồng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-subtract-6-k0",
        "section": "explore",
        "title": "Số đối",
        "text": "Hai số có tổng bằng 0 là hai số đối nhau. Số đối của 2/3 là -2/3; số đối của 0 là 0.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-subtract-6-k1",
        "section": "explore",
        "title": "Phép trừ",
        "text": "Muốn trừ một phân số cho một phân số, ta cộng số bị trừ với số đối của số trừ. Cùng mẫu: trừ tử và giữ mẫu. Khác mẫu: quy đồng trước. Rút gọn kết quả.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-subtract-6-ex0",
        "section": "example",
        "title": "1. Quy đồng rồi trừ",
        "text": "5/6 − 1/4 = 10/12 − 3/12 = (10 − 3)/12 = 7/12.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-subtract-6-ex1",
        "section": "example",
        "title": "2. Trừ một phân số âm",
        "text": "1/3 − (-1/2) = 1/3 + 1/2 = 2/6 + 3/6 = 5/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-subtract-6-guide",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Tìm số đối, trừ phân số và tìm thành phần chưa biết.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tính (3/5) − (1/5).",
        "answer": "2/5",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(3/5) − (1/5) = (3 − (1))/5 = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q1",
        "section": "foundation",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (2/3) − (5/6).",
        "answer": "-1/6",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(2/3) − (5/6) = (4 − (5))/6 = -1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q2",
        "section": "guided",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (2/1) − (3/5).",
        "answer": "7/5",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(2/1) − (3/5) = (10 − (3))/5 = 7/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm x: x + (-1/4) = 1/2.",
        "answer": "3/4",
        "hint": "Lấy tổng trừ số hạng đã biết.",
        "solution": "x = (1/2) − (-1/4) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q4",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (3/5) − (1/5).",
        "answer": "2/5",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(3/5) − (1/5) = (3 − (1))/5 = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q5",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (5/7) − (2/7).",
        "answer": "3/7",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(5/7) − (2/7) = (5 − (2))/7 = 3/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q6",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (1/2) − (1/3).",
        "answer": "1/6",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(1/2) − (1/3) = (3 − (2))/6 = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q7",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (5/6) − (1/4).",
        "answer": "7/12",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(5/6) − (1/4) = (10 − (3))/12 = 7/12.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q8",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (2/3) − (5/6).",
        "answer": "-1/6",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(2/3) − (5/6) = (4 − (5))/6 = -1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q9",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-1/2) − (1/4).",
        "answer": "-3/4",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(-1/2) − (1/4) = (-2 − (1))/4 = -3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q10",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (1/3) − (-1/6).",
        "answer": "1/2",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(1/3) − (-1/6) = (2 − (-1))/6 = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q11",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-3/4) − (-1/2).",
        "answer": "-1/4",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(-3/4) − (-1/2) = (-3 − (-2))/4 = -1/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q12",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (7/8) − (1/6).",
        "answer": "17/24",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(7/8) − (1/6) = (21 − (4))/24 = 17/24.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (2/1) − (3/5).",
        "answer": "7/5",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(2/1) − (3/5) = (10 − (3))/5 = 7/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q14",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (3/4) − (3/4).",
        "answer": "0",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(3/4) − (3/4) = (3 − (3))/4 = 0.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-subtract-6-q15",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (0/1) − (2/7).",
        "answer": "-2/7",
        "hint": "Quy đồng rồi trừ tử, giữ nguyên mẫu.",
        "solution": "(0/1) − (2/7) = (0 − (2))/7 = -2/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q16",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: x + (1/3) = 5/6.",
        "answer": "1/2",
        "hint": "Lấy tổng trừ số hạng đã biết.",
        "solution": "x = (5/6) − (1/3) = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q17",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: x + (2/5) = 1/2.",
        "answer": "1/10",
        "hint": "Lấy tổng trừ số hạng đã biết.",
        "solution": "x = (1/2) − (2/5) = 1/10.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q18",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: x + (-1/4) = 1/2.",
        "answer": "3/4",
        "hint": "Lấy tổng trừ số hạng đã biết.",
        "solution": "x = (1/2) − (-1/4) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q19",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: x + (3/7) = 6/7.",
        "answer": "3/7",
        "hint": "Lấy tổng trừ số hạng đã biết.",
        "solution": "x = (6/7) − (3/7) = 3/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q20",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 5/6 m dây, cắt đi 1/3 m. Còn bao nhiêu mét dây?",
        "answer": "1/2",
        "hint": "Lấy độ dài ban đầu trừ độ dài đã cắt.",
        "solution": "Độ dài còn lại là:\n5/6 − 1/3 = 5/6 − 2/6 = 1/2 (m).\nĐáp số: 1/2 m.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q21",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một bình có 3/4 lít nước, rót ra 1/2 lít. Còn bao nhiêu lít?",
        "answer": "1/4",
        "hint": "Thực hiện phép trừ.",
        "solution": "Lượng nước còn lại là:\n3/4 − 1/2 = 3/4 − 2/4 = 1/4 (lít).\nĐáp số: 1/4 lít.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1 − 1/2 − 1/3.",
        "answer": "1/6",
        "hint": "Thực hiện từ trái sang phải.",
        "solution": "1 − 1/2 − 1/3 = 1/2 − 1/3 = 3/6 − 2/6 = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q23",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phép trừ phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm x: 3/4 − x = 1/6.",
        "answer": "7/12",
        "hint": "Số trừ bằng số bị trừ trừ hiệu.",
        "solution": "x = 3/4 − 1/6 = 9/12 − 2/12 = 7/12.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-subtract-6-q24",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phép trừ phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-multiply-6",
    "title": "Nhân và chia phân số có số âm",
    "grade": 6,
    "topic": "Phân số mở rộng",
    "goal": "Ôn kiến thức phân số tiểu học. Nhân, chia phân số; rút gọn các thừa số trước khi nhân. Mở rộng với phân số có tử hoặc mẫu là số nguyên âm.",
    "textbook": "Bài tự biên soạn theo chủ đề Phân số lớp 6; không gắn với trang hay ấn bản sách cụ thể.",
    "teacherNotes": "Học sau Số nguyên và Tính chia hết. Phân số đã được học từ lớp 4; lớp 6 mở rộng sang tử, mẫu là số nguyên và bài toán tìm số ban đầu. Các câu cơ bản dùng để ôn tập.",
    "knowledgeSummary": "Phép nhân: Nhân tử với tử, mẫu với mẫu. Có thể rút gọn thừa số chung ở tử và mẫu trước khi nhân. Chú ý quy tắc dấu.\nNghịch đảo và phép chia: Hai số có tích bằng 1 là hai số nghịch đảo. Số 0 không có số nghịch đảo. Muốn chia cho một phân số khác 0, nhân với số nghịch đảo của phân số đó.\nVí dụ: (-3/7) × (14/9) = (-~3~ × ~7~ × 2)/(~7~ × ~3~ × 3) = -2/3.\nLưu ý: Mẫu số phải khác 0; rút gọn kết quả.",
    "blocks": [
      {
        "id": "math-fraction-multiply-6-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ở tiểu học, em đã học phân số với tử là số tự nhiên, mẫu là số tự nhiên khác 0. Bài này ôn lại kiến thức đó rồi mở rộng. Ôn phép tính với số nguyên; có thể dùng ƯCLN để rút gọn và BCNN để quy đồng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-6-k0",
        "section": "explore",
        "title": "Phép nhân",
        "text": "Nhân tử với tử, mẫu với mẫu. Có thể rút gọn thừa số chung ở tử và mẫu trước khi nhân. Chú ý quy tắc dấu.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-6-k1",
        "section": "explore",
        "title": "Nghịch đảo và phép chia",
        "text": "Hai số có tích bằng 1 là hai số nghịch đảo. Số 0 không có số nghịch đảo. Muốn chia cho một phân số khác 0, nhân với số nghịch đảo của phân số đó.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-6-ex0",
        "section": "example",
        "title": "1. Rút gọn trước khi nhân",
        "text": "(-3/7) × (14/9) = (-~3~ × ~7~ × 2)/(~7~ × ~3~ × 3) = -2/3.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-6-ex1",
        "section": "example",
        "title": "2. Đổi chia thành nhân",
        "text": "(-5/8) : (-15/4) = (-5/8) × (-4/15) = (~5~ × ~4~)/(~4~ × 2 × ~5~ × 3) = 1/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-6-guide",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Nhân, chia phân số; rút gọn các thừa số trước khi nhân.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tính (2/3) × (3/5).",
        "answer": "2/5",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(2/3) × (3/5) = (2 × ~3~)/(~3~ × 5) = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q1",
        "section": "foundation",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (5/8) × (4/15).",
        "answer": "1/6",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(5/8) × (4/15) = (~5~ × ~4~)/(~4~ × 2 × ~5~ × 3) = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q2",
        "section": "guided",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (3/5) : (10/9).",
        "answer": "27/50",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(3/5) : (10/9) = (3/5) × (9/10) = (3 × 9)/(5 × 10) = 27/50.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (0/1) × (2/5).",
        "answer": "0",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(0/1) × (2/5) = (0 × 2)/(1 × 5) = 0.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-multiply-6-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính (2/3) × (3/5).",
        "answer": "2/5",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(2/3) × (3/5) = (2 × ~3~)/(~3~ × 5) = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q5",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (2/3) : (3/5).",
        "answer": "10/9",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(2/3) : (3/5) = (2/3) × (5/3) = (2 × 5)/(3 × 3) = 10/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q6",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-3/4) × (2/9).",
        "answer": "-1/6",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(-3/4) × (2/9) = (-~3~ × ~2~)/(~2~ × 2 × ~3~ × 3) = -1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q7",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-3/4) : (2/9).",
        "answer": "-27/8",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(-3/4) : (2/9) = (-3/4) × (9/2) = (-3 × 9)/(4 × 2) = -27/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q8",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (5/8) × (4/15).",
        "answer": "1/6",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(5/8) × (4/15) = (~5~ × ~4~)/(~4~ × 2 × ~5~ × 3) = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q9",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (5/8) : (4/15).",
        "answer": "75/32",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(5/8) : (4/15) = (5/8) × (15/4) = (5 × 15)/(8 × 4) = 75/32.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q10",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-2/7) × (-7/3).",
        "answer": "2/3",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(-2/7) × (-7/3) = (2 × ~7~)/(~7~ × 3) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q11",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (-2/7) : (-7/3).",
        "answer": "6/49",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(-2/7) : (-7/3) = (-2/7) × (-3/7) = (-2 × -3)/(7 × 7) = 6/49.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q12",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (3/5) × (10/9).",
        "answer": "2/3",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(3/5) × (10/9) = (~3~ × ~5~ × 2)/(~5~ × ~3~ × 3) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (3/5) : (10/9).",
        "answer": "27/50",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(3/5) : (10/9) = (3/5) × (9/10) = (3 × 9)/(5 × 10) = 27/50.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q14",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (7/12) × (6/7).",
        "answer": "1/2",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(7/12) × (6/7) = (~7~ × ~6~)/(~6~ × 2 × ~7~) = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q15",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (7/12) : (6/7).",
        "answer": "49/72",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(7/12) : (6/7) = (7/12) × (7/6) = (7 × 7)/(12 × 6) = 49/72.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q16",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (4/9) × (3/8).",
        "answer": "1/6",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(4/9) × (3/8) = (~4~ × ~3~)/(~3~ × 3 × ~4~ × 2) = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q17",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (4/9) : (3/8).",
        "answer": "32/27",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(4/9) : (3/8) = (4/9) × (8/3) = (4 × 8)/(9 × 3) = 32/27.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q18",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (0/1) × (2/5).",
        "answer": "0",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(0/1) × (2/5) = (0 × 2)/(1 × 5) = 0.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-multiply-6-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (0/1) : (2/5).",
        "answer": "0",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(0/1) : (2/5) = (0/1) × (5/2) = (0 × 5)/(1 × 2) = 0.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-multiply-6-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (3/4) × (2/1).",
        "answer": "3/2",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(3/4) × (2/1) = (3 × ~2~)/(~2~ × 2 × 1) = 3/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q21",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (3/4) : (2/1).",
        "answer": "3/8",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(3/4) : (2/1) = (3/4) × (1/2) = (3 × 1)/(4 × 2) = 3/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (2/3) × (1/1).",
        "answer": "2/3",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(2/3) × (1/1) = (2 × 1)/(3 × 1) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q23",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tính (2/3) : (1/1).",
        "answer": "2/3",
        "hint": "Nếu là phép chia, nhân với số nghịch đảo của số chia. Rút gọn trước khi nhân.",
        "solution": "(2/3) : (1/1) = (2/3) × (1/1) = (2 × 1)/(3 × 1) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-6-q24",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Phép nhân và phép chia phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-applications-6",
    "title": "Hai bài toán cơ bản về phân số",
    "grade": 6,
    "topic": "Phân số mở rộng",
    "goal": "Ôn kiến thức phân số tiểu học. Phân biệt tìm giá trị phân số của một số và tìm số khi biết giá trị phân số của nó.",
    "textbook": "Bài tự biên soạn theo chủ đề Phân số lớp 6; không gắn với trang hay ấn bản sách cụ thể.",
    "teacherNotes": "Học sau Số nguyên và Tính chia hết. Phân số đã được học từ lớp 4; lớp 6 mở rộng sang tử, mẫu là số nguyên và bài toán tìm số ban đầu. Các câu cơ bản dùng để ôn tập.",
    "knowledgeSummary": "Tìm giá trị phân số: Muốn tìm a/b của một số, nhân số đó với a/b.\nTìm số ban đầu: Biết a/b của một số bằng c (a/b khác 0), số cần tìm bằng c : (a/b). Đọc kĩ xem đề cho toàn bộ hay chỉ cho một phần.\nPhần còn lại: Xem toàn bộ là 1. Phần còn lại bằng 1 trừ phần đã dùng. Trước khi tìm toàn bộ, xác định giá trị đã cho ứng với phân số nào.\nVí dụ: Tìm 3/4 của 28: 28 × (3/4) = 21.\nLưu ý: Mẫu số phải khác 0; rút gọn kết quả.",
    "blocks": [
      {
        "id": "math-fraction-applications-6-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ở tiểu học, em đã học phân số với tử là số tự nhiên, mẫu là số tự nhiên khác 0. Bài này ôn lại kiến thức đó rồi mở rộng. Ôn phép tính với số nguyên; có thể dùng ƯCLN để rút gọn và BCNN để quy đồng.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-k0",
        "section": "explore",
        "title": "Tìm giá trị phân số",
        "text": "Muốn tìm a/b của một số, nhân số đó với a/b.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-k1",
        "section": "explore",
        "title": "Tìm số ban đầu",
        "text": "Biết a/b của một số bằng c (a/b khác 0), số cần tìm bằng c : (a/b). Đọc kĩ xem đề cho toàn bộ hay chỉ cho một phần.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-k2",
        "section": "explore",
        "title": "Phần còn lại",
        "text": "Xem toàn bộ là 1. Phần còn lại bằng 1 trừ phần đã dùng. Trước khi tìm toàn bộ, xác định giá trị đã cho ứng với phân số nào.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-ex0",
        "section": "example",
        "title": "1. Tìm một phần",
        "text": "Tìm 3/4 của 28: 28 × (3/4) = 21.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-ex1",
        "section": "example",
        "title": "2. Tìm toàn bộ",
        "text": "Biết 2/5 của một số là 14. Số đó là: 14 : (2/5) = 14 × (5/2) = 35.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-ex2",
        "section": "example",
        "title": "3. Tìm từ phần còn lại",
        "text": "Dùng 1/3 cuộn dây, còn 12 m. Phần còn lại: 1 − 1/3 = 2/3.\nĐộ dài cuộn dây: 12 : (2/3) = 18 (m).",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-applications-6-guide",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Phân biệt tìm giá trị phân số của một số và tìm số khi biết giá trị phân số của nó.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tìm 1/3 của 12.",
        "answer": "4",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "12 × (1/3) = 4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q1",
        "section": "foundation",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm 3/4 của 48.",
        "answer": "36",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "48 × (3/4) = 36.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q2",
        "section": "guided",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm một số biết 3/7 của số đó bằng 18.",
        "answer": "42",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 18 : (3/7) = 18 × (7/3) = 42.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q3",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Có 18 bạn tham gia, bằng 3/4 số học sinh của lớp. Lớp có bao nhiêu học sinh?",
        "answer": "24",
        "hint": "Biết giá trị một phân số, tìm toàn bộ.",
        "solution": "Số học sinh của lớp là:\n18 : (3/4) = 18 × (4/3) = 24 (học sinh).\nĐáp số: 24 học sinh.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm 1/3 của 12.",
        "answer": "4",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "12 × (1/3) = 4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q5",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 3/5 của 20.",
        "answer": "12",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "20 × (3/5) = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q6",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 5/6 của 24.",
        "answer": "20",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "24 × (5/6) = 20.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q7",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/7 của 35.",
        "answer": "10",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "35 × (2/7) = 10.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q8",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 3/4 của 48.",
        "answer": "36",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "48 × (3/4) = 36.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q9",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/3 của 18.",
        "answer": "12",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "18 × (2/3) = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q10",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 2/3 của số đó bằng 8.",
        "answer": "12",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 8 : (2/3) = 8 × (3/2) = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q11",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 3/4 của số đó bằng 15.",
        "answer": "20",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 15 : (3/4) = 15 × (4/3) = 20.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q12",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 2/5 của số đó bằng 12.",
        "answer": "30",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 12 : (2/5) = 12 × (5/2) = 30.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q13",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 3/7 của số đó bằng 18.",
        "answer": "42",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 18 : (3/7) = 18 × (7/3) = 42.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q14",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 4/5 của số đó bằng 20.",
        "answer": "25",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 20 : (4/5) = 20 × (5/4) = 25.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q15",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm một số biết 7/8 của số đó bằng 21.",
        "answer": "24",
        "hint": "Lấy giá trị đã biết chia cho phân số.",
        "solution": "Số cần tìm là: 21 : (7/8) = 21 × (8/7) = 24.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q16",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Lớp có 36 học sinh, 2/3 số học sinh tham gia câu lạc bộ. Có bao nhiêu học sinh tham gia?",
        "answer": "24",
        "hint": "Tìm 2/3 của 36.",
        "solution": "Số học sinh tham gia là:\n36 × (2/3) = 24 (học sinh).\nĐáp số: 24 học sinh.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Lan đọc 3/5 quyển sách gồm 120 trang. Lan đã đọc bao nhiêu trang?",
        "answer": "72",
        "hint": "Tìm 3/5 của 120.",
        "solution": "Số trang đã đọc là:\n120 × (3/5) = 72 (trang).\nĐáp số: 72 trang.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 18 bạn tham gia, bằng 3/4 số học sinh của lớp. Lớp có bao nhiêu học sinh?",
        "answer": "24",
        "hint": "Biết giá trị một phân số, tìm toàn bộ.",
        "solution": "Số học sinh của lớp là:\n18 : (3/4) = 18 × (4/3) = 24 (học sinh).\nĐáp số: 24 học sinh.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một đoạn đường dài 15 km, bằng 3/5 cả quãng đường. Cả quãng đường dài bao nhiêu km?",
        "answer": "25",
        "hint": "Lấy 15 chia cho 3/5.",
        "solution": "Quãng đường dài là:\n15 : (3/5) = 25 (km).\nĐáp số: 25 km.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một rổ có 40 quả, đã bán 3/8 số quả. Còn lại bao nhiêu quả?",
        "answer": "25",
        "hint": "Tính số đã bán rồi trừ.",
        "solution": "Số quả đã bán là:\n40 × (3/8) = 15 (quả).\nSố quả còn lại là:\n40 − 15 = 25 (quả).\nĐáp số: 25 quả.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q21",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một lớp có 12 bạn nữ và 18 bạn nam. Số bạn nữ bằng bao nhiêu phần số học sinh cả lớp?",
        "answer": "2/5",
        "hint": "Tính tổng số học sinh trước.",
        "solution": "Tổng số học sinh: 12 + 18 = 30.\nPhân số cần tìm: 12/30 = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-applications-6-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một bể chứa đầy nước. Dùng hết 2/5 lượng nước thì còn 90 lít. Bể đầy chứa bao nhiêu lít?",
        "answer": "150",
        "hint": "90 lít ứng với 1 − 2/5 của bể.",
        "solution": "Phần nước còn lại: 1 − 2/5 = 3/5.\nDung tích bể là:\n90 : (3/5) = 150 (lít).\nĐáp số: 150 lít.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Lan đọc 1/3 quyển sách ngày đầu, 1/4 quyển sách ngày thứ hai, còn 50 trang. Quyển sách có bao nhiêu trang?",
        "answer": "120",
        "hint": "Tính phân số chỉ số trang còn lại.",
        "solution": "Phần sách còn lại: 1 − 1/3 − 1/4 = 5/12.\nSố trang của sách là:\n50 : (5/12) = 120 (trang).\nĐáp số: 120 trang.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-applications-6-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Hai bài toán cơ bản về phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  }
];
