import type { MathLessonData } from './lessons';

export const measurementLesson: MathLessonData = {
  "id": "math-measurement-units-3",
  "title": "Một số đơn vị đo độ dài, khối lượng, dung tích",
  "grade": 3,
  "semester": "1",
  "topic": "Đo lường",
  "goal": "Điền số thích hợp, tính với số đo mm, g, ml, chọn số đo hợp lý và giải bài toán có lời văn.",
  "textbook": "Bài tự biên soạn, tham khảo Toán 3 Kết nối tri thức, tập 1, các bài Mi-li-mét, Gam, Mi-li-lít.",
  "teacherNotes": "Tham khảo: https://olm.vn/bg/toan-3; https://olm.vn/chu-de/mi-li-lit-3949213199; https://olm.vn/chu-de/16-luyen-tap-3921613240. Cho học sinh xem thước có vạch mm, cân và ca đong. Các số đo vật dụng trong ví dụ là tình huống minh họa. Không đổi giữa đơn vị khối lượng và dung tích.",
  "knowledgeSummary": "1 cm = 10 mm; 1 dm = 100 mm; 1 m = 1 000 mm = 100 cm; 1 km = 1 000 m.\n1 kg = 1 000 g; 1 l = 1 000 ml.\nCộng, trừ số đo cùng đơn vị: tính các số và giữ đơn vị. Nhân, chia số đo với một số: tính và ghi đơn vị sau kết quả. Phép tính chỉ có cộng, trừ thì làm từ trái sang phải.\nVí dụ: 6 cm = 60 mm; 250 mm + 100 mm = 350 mm; 37 g + 63 g − 30 g = 70 g; 50 mm : 2 = 25 mm.\nLưu ý: Chọn số đo phù hợp với đồ vật; phân biệt mm, g, ml. Luôn ghi đơn vị sau kết quả.",
  "blocks": [
    {
      "id": "measure-direct-b1",
      "section": "foundation",
      "title": "Nhớ tên và kí hiệu đơn vị",
      "text": "Độ dài: mm, cm, dm, m, km.\nKhối lượng: g, kg.\nDung tích: ml, l.\nVí dụ: bút chì dài 15 cm, thước dài 2 dm, dây dài 2 m, đường dài 3 km, túi gạo nặng 5 kg, bình nước chứa 2 l.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b2",
      "section": "explore",
      "title": "Điền số thích hợp",
      "text": "1 cm = 10 mm; 1 dm = 100 mm; 1 m = 1 000 mm.\n1 m = 100 cm; 1 km = 1 000 m.\n1 kg = 1 000 g; 1 l = 1 000 ml.\nVí dụ: 6 cm = 60 mm vì mỗi xăng-ti-mét bằng 10 mi-li-mét.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b3",
      "section": "explore",
      "title": "Cộng, trừ các số đo cùng đơn vị",
      "text": "Cộng hoặc trừ các số, rồi viết đơn vị đo sau kết quả.\n250 mm + 100 mm = 350 mm.\n64 mm − 15 mm = 49 mm.\nVới phép tính chỉ có cộng và trừ, tính từ trái sang phải:\n37 g + 63 g − 30 g = 100 g − 30 g = 70 g.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b4",
      "section": "explore",
      "title": "Nhân, chia số đo với một số",
      "text": "Nhân hoặc chia số đo với số đã cho, rồi viết đơn vị đo sau kết quả.\n11 mm × 3 = 33 mm.\n50 mm : 2 = 25 mm.\nTrong bài này, các phép chia đều là phép chia hết.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b5",
      "section": "explore",
      "title": "Chọn số đo hợp lý",
      "text": "Hãy hình dung vật cần đo và chú ý cả số lẫn đơn vị.\nMột quyển sách mỏng có thể dày khoảng 5 mm; 5 cm, 5 dm hay 5 m đều quá dày.\nMột quả táo có thể nặng khoảng 200 g; một bình nước có thể chứa 2 l. Đây là số đo ước lượng, không phải mọi vật đều có cùng số đo.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b6",
      "section": "example",
      "title": "1. Điền số vào chỗ trống",
      "text": "6 cm = … mm.\n1 cm = 10 mm, nên 6 cm = 60 mm.\nSố cần điền là 60.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b7",
      "section": "example",
      "title": "2. Tính cộng, trừ",
      "text": "250 mm + 100 mm = 350 mm.\n64 mm − 15 mm = 49 mm.\n37 g + 63 g − 30 g = 100 g − 30 g = 70 g.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b8",
      "section": "example",
      "title": "3. Tính nhân, chia",
      "text": "11 mm × 3 = 33 mm.\n50 mm : 2 = 25 mm.\n150 ml × 2 = 300 ml; 600 ml : 3 = 200 ml.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b9",
      "section": "example",
      "title": "4. Chọn số đo phù hợp",
      "text": "Một quyển sách Toán 3 tập 1 mỏng dày khoảng bao nhiêu?\nA. 5 mm; B. 5 cm; C. 5 dm; D. 5 m.\nChọn A. 5 mm là độ dày hợp lý của một quyển sách mỏng.",
      "visual": "none",
      "values": []
    },
    {
      "id": "measure-direct-b10",
      "section": "guided",
      "title": "Em thử làm",
      "text": "Tính 28 g + 42 g − 20 g.\nTrước hết tính 28 + 42, sau đó trừ 20. Nhớ ghi đơn vị g sau kết quả.",
      "visual": "none",
      "values": []
    }
  ],
  "exercises": [
    {
      "id": "measure-direct-e1",
      "section": "foundation",
      "kind": "number",
      "prompt": "Điền số: 1 cm = … mm.",
      "answer": "10",
      "hint": "1 cm bằng 10 mm.",
      "solution": "1 cm = 10 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "measure-direct-e2",
      "section": "guided",
      "kind": "number",
      "prompt": "Tính: 28 g + 42 g − 20 g.",
      "answer": "50",
      "hint": "Tính từ trái sang phải.",
      "solution": "28 g + 42 g − 20 g = 70 g − 20 g = 50 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "measure-direct-e3",
      "section": "practice",
      "kind": "number",
      "prompt": "Tính: 18 ml × 3.",
      "answer": "54",
      "hint": "Tính 18 × 3 rồi ghi đơn vị ml.",
      "solution": "18 ml × 3 = 54 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "measure-direct-e4",
      "section": "practice",
      "kind": "choice",
      "prompt": "Một cục tẩy thường dài khoảng bao nhiêu?",
      "answer": "4 cm",
      "hint": "Hình dung cục tẩy em thường dùng.",
      "solution": "Chọn 4 cm: đây là độ dài hợp lý của một cục tẩy.",
      "options": [
        "4 mm",
        "4 cm",
        "4 m",
        "4 km"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "measure-direct-e5",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 cm = … mm.",
      "answer": "10",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 cm = 10 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e6",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 m = … mm.",
      "answer": "1000",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 m = 1 000 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e7",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 6 cm = … mm.",
      "answer": "60",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "6 cm = 60 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e8",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 dm = … mm.",
      "answer": "100",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 dm = 100 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e9",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 m = … cm.",
      "answer": "100",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 m = 100 cm.",
      "options": [],
      "unit": "cm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e10",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 km = … m.",
      "answer": "1000",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 km = 1 000 m.",
      "options": [],
      "unit": "m",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e11",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 kg = … g.",
      "answer": "1000",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 kg = 1 000 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e12",
      "section": "extra",
      "kind": "number",
      "prompt": "Điền số: 1 l = … ml.",
      "answer": "1000",
      "hint": "Nhớ mối liên hệ giữa hai đơn vị.",
      "solution": "1 l = 1 000 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "easy",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e13",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 250 mm + 100 mm.",
      "answer": "350",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "250 mm + 100 mm = 350 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e14",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 64 mm − 15 mm.",
      "answer": "49",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "64 mm − 15 mm = 49 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e15",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 11 mm × 3.",
      "answer": "33",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "11 mm × 3 = 33 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e16",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 50 mm : 2.",
      "answer": "25",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "50 mm : 2 = 25 mm.",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e17",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 37 g + 63 g − 30 g.",
      "answer": "70",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "37 g + 63 g − 30 g = 100 g − 30 g = 70 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e18",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 180 g − 45 g.",
      "answer": "135",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "180 g − 45 g = 135 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e19",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 24 g × 3.",
      "answer": "72",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "24 g × 3 = 72 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e20",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 84 g : 4.",
      "answer": "21",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "84 g : 4 = 21 g.",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e21",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 120 ml + 80 ml − 50 ml.",
      "answer": "150",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "120 ml + 80 ml − 50 ml = 200 ml − 50 ml = 150 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e22",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 500 ml − 125 ml.",
      "answer": "375",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "500 ml − 125 ml = 375 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e23",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 150 ml × 3.",
      "answer": "450",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "150 ml × 3 = 450 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e24",
      "section": "extra",
      "kind": "number",
      "prompt": "Tính: 600 ml : 3.",
      "answer": "200",
      "hint": "Tính với các số rồi ghi đơn vị; nếu chỉ có cộng, trừ thì tính từ trái sang phải.",
      "solution": "600 ml : 3 = 200 ml.",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e25",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một quyển sách Toán 3 tập 1 mỏng dày khoảng bao nhiêu?",
      "answer": "5 mm",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "5 mm là độ dày hợp lý của một quyển sách mỏng; các số đo còn lại quá lớn.",
      "options": [
        "5 mm",
        "5 cm",
        "5 dm",
        "5 m"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e26",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một chiếc bút chì mới thường dài khoảng bao nhiêu?",
      "answer": "15 cm",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "15 cm là độ dài hợp lý của một chiếc bút chì.",
      "options": [
        "15 mm",
        "15 cm",
        "15 m",
        "15 km"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e27",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một chiếc thước kẻ học sinh thường dài khoảng bao nhiêu?",
      "answer": "2 dm",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "2 dm bằng 20 cm, là độ dài hợp lý của một chiếc thước kẻ học sinh.",
      "options": [
        "2 mm",
        "2 cm",
        "2 dm",
        "2 km"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e28",
      "section": "extra",
      "kind": "choice",
      "prompt": "Quãng đường từ nhà đến trường ở một xã dài khoảng bao nhiêu là hợp lý?",
      "answer": "2 km",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "Trong các lựa chọn, 2 km là quãng đường hợp lý; các số đo còn lại quá ngắn.",
      "options": [
        "2 mm",
        "2 cm",
        "2 dm",
        "2 km"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e29",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một quả táo thường nặng khoảng bao nhiêu?",
      "answer": "200 g",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "200 g là khối lượng hợp lý của một quả táo. ml và mm không đo khối lượng.",
      "options": [
        "200 g",
        "200 kg",
        "200 ml",
        "200 mm"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e30",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một bao gạo nhỏ bán ở cửa hàng có thể nặng bao nhiêu?",
      "answer": "5 kg",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "5 kg là khối lượng hợp lý của một bao gạo nhỏ.",
      "options": [
        "5 g",
        "5 kg",
        "5 ml",
        "5 cm"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e31",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một hộp sữa nhỏ thường chứa khoảng bao nhiêu sữa?",
      "answer": "180 ml",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "180 ml là dung tích hợp lý của một hộp sữa nhỏ.",
      "options": [
        "180 mm",
        "180 g",
        "180 ml",
        "180 l"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-direct-e32",
      "section": "extra",
      "kind": "choice",
      "prompt": "Một bình nước uống để bàn có thể chứa khoảng bao nhiêu nước?",
      "answer": "2 l",
      "hint": "Chú ý loại đại lượng, đơn vị và kích thước thực tế.",
      "solution": "2 l là dung tích hợp lý của một bình nước để bàn.",
      "options": [
        "2 mm",
        "2 ml",
        "2 l",
        "2 km"
      ],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Điền số, tính với số đo và chọn số đo hợp lý",
      "difficulty": "medium",
      "workspace": "small"
    },
    {
      "id": "measure-word-e1",
      "section": "extra",
      "kind": "number",
      "prompt": "Một đoạn dây dài 250 mm. Lan cắt đi 100 mm. Đoạn dây còn lại dài bao nhiêu mi-li-mét?",
      "answer": "150",
      "hint": "Lấy độ dài ban đầu trừ độ dài đã cắt.",
      "solution": "Bài giải:\nĐoạn dây còn lại dài là:\n250 − 100 = 150 (mm).\nĐáp số: 150 mm.",
      "solutionStyle": "method",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "measure-word-e2",
      "section": "extra",
      "kind": "number",
      "prompt": "Ba tấm bìa, mỗi tấm dày 2 mm, được xếp chồng khít lên nhau. Chồng bìa dày bao nhiêu mi-li-mét?",
      "answer": "6",
      "hint": "Lấy độ dày một tấm nhân với số tấm.",
      "solution": "Bài giải:\nChồng bìa dày là:\n2 × 3 = 6 (mm).\nĐáp số: 6 mm.",
      "solutionStyle": "method",
      "options": [],
      "unit": "mm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "measure-word-e3",
      "section": "extra",
      "kind": "number",
      "prompt": "Một gói bánh nặng 125 g, một gói kẹo nặng 75 g. Cả hai gói nặng bao nhiêu gam?",
      "answer": "200",
      "hint": "Cộng khối lượng hai gói.",
      "solution": "Bài giải:\nCả hai gói nặng là:\n125 + 75 = 200 (g).\nĐáp số: 200 g.",
      "solutionStyle": "method",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "measure-word-e4",
      "section": "extra",
      "kind": "number",
      "prompt": "Mẹ chia đều 600 g đậu vào 3 túi. Mỗi túi có bao nhiêu gam đậu?",
      "answer": "200",
      "hint": "Chia số gam đậu cho số túi.",
      "solution": "Bài giải:\nSố đậu trong mỗi túi là:\n600 : 3 = 200 (g).\nĐáp số: 200 g đậu.",
      "solutionStyle": "method",
      "options": [],
      "unit": "g",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "measure-word-e5",
      "section": "extra",
      "kind": "number",
      "prompt": "Một bình có 500 ml nước. Mai rót ra 150 ml nước. Trong bình còn bao nhiêu mi-li-lít nước?",
      "answer": "350",
      "hint": "Lấy lượng nước ban đầu trừ lượng đã rót ra.",
      "solution": "Bài giải:\nSố nước còn lại trong bình là:\n500 − 150 = 350 (ml).\nĐáp số: 350 ml nước.",
      "solutionStyle": "method",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "measure-word-e6",
      "section": "extra",
      "kind": "number",
      "prompt": "Mỗi hộp sữa chứa 180 ml sữa. Ba hộp như vậy chứa bao nhiêu mi-li-lít sữa?",
      "answer": "540",
      "hint": "Lấy lượng sữa trong một hộp nhân với 3.",
      "solution": "Bài giải:\nSố sữa trong ba hộp là:\n180 × 3 = 540 (ml).\nĐáp số: 540 ml sữa.",
      "solutionStyle": "method",
      "options": [],
      "unit": "ml",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Bài toán có lời văn với mm, g, ml",
      "difficulty": "medium",
      "workspace": "medium"
    }
  ]
};

export function addMeasurementLesson(lessons: MathLessonData[]): MathLessonData[] {
  if (lessons.length >= 100 || lessons.some(l => l.id === measurementLesson.id)) return lessons;
  const next = [...lessons];
  const index = next.findIndex(l => l.id === 'math-unit-fractions-3');
  next.splice(index < 0 ? next.length : index + 1, 0, structuredClone(measurementLesson));
  return next;
}

// New exercise IDs keep answers to the former questions out of this revised set.
export function reviseMeasurementPractice(lessons: MathLessonData[]): MathLessonData[] {
  return lessons.map(lesson => {
    if (lesson.id !== measurementLesson.id) return lesson;
    const customBlocks = lesson.blocks.filter(b => !/^measure-3-b\d+$/.test(b.id));
    const customExercises = lesson.exercises.filter(e => !/^measure-3-e\d+$/.test(e.id));
    const blocks = measurementLesson.blocks.filter(b => !customBlocks.some(old => old.id === b.id));
    const exercises = measurementLesson.exercises.filter(e => !customExercises.some(old => old.id === e.id));
    return { ...lesson, goal: measurementLesson.goal, knowledgeSummary: measurementLesson.knowledgeSummary,
      blocks: [...structuredClone(blocks), ...customBlocks],
      exercises: [...structuredClone(exercises), ...customExercises] };
  });
}

export function addMeasurementWordProblems(lessons: MathLessonData[]): MathLessonData[] {
  return lessons.map(lesson => {
    if (lesson.id !== measurementLesson.id) return lesson;
    const additions = measurementLesson.exercises.filter(e => e.id.startsWith('measure-word-') &&
      !lesson.exercises.some(existing => existing.id === e.id));
    if (!additions.length || lesson.exercises.length + additions.length > 100) return lesson;
    return { ...lesson, exercises: [...lesson.exercises, ...structuredClone(additions)] };
  });
}
