import type { MathLessonData } from './lessons';

export const midpointLesson: MathLessonData = {
  id: 'math-midpoint-3',
  title: 'Điểm ở giữa, trung điểm của đoạn thẳng',
  grade: 3,
  semester: '1',
  topic: 'Hình học',
  goal: 'Nhận biết ba điểm thẳng hàng, điểm ở giữa và trung điểm; xác định trung điểm và tính độ dài đơn giản.',
  textbook:
    'Bài tự biên soạn, tham khảo Toán 3 Kết nối tri thức, tập 1, Bài 16.',
  teacherNotes:
    'Tham khảo: https://olm.vn/chu-de/diem-o-giua-trung-diem-cua-doan-thang-2061561479. Nhấn mạnh hai điều kiện của trung điểm. Hình minh họa trên màn hình và PDF không dùng để đo trực tiếp; sử dụng số đo ghi trong đề. Các bài tính dùng cm.',
  knowledgeSummary:
    'Ba điểm cùng nằm trên một đường thẳng là ba điểm thẳng hàng.\nM ở giữa A và B khi A, M, B thẳng hàng theo thứ tự A – M – B (hoặc B – M – A).\nM là trung điểm của AB khi M ở giữa A, B và AM = MB.\nKhi có trung điểm, hai đoạn nhỏ đều bằng độ dài cả đoạn chia cho 2; độ dài cả đoạn bằng một nửa đoạn nhân với 2.\nVí dụ: AB = 8 cm, M là trung điểm thì AM = MB = 4 cm.\nLưu ý: Điểm ở giữa chưa chắc là trung điểm. Cách đều hai đầu nhưng không ở giữa cũng không phải trung điểm. Dùng số đo của đề, không đo hình minh họa.',
  blocks: [
    {
      id: 'midpoint-b1',
      section: 'foundation',
      title: 'Ba điểm thẳng hàng',
      text: 'Ba điểm cùng nằm trên một đường thẳng là ba điểm thẳng hàng. Trên hình, A, M, B thẳng hàng theo thứ tự từ trái sang phải.',
      visual: 'segment',
      values: [2, 4, 0, 0],
      segmentLabels: ['A', 'M', 'B'],
    },
    {
      id: 'midpoint-b2',
      section: 'explore',
      title: 'Điểm ở giữa',
      text: 'Trên hình, P, Q, R thẳng hàng và Q nằm giữa hai điểm P, R. Ta nói Q là điểm ở giữa P và R.\nĐiểm ở giữa không nhất thiết chia đoạn thẳng thành hai phần bằng nhau.',
      visual: 'segment',
      values: [2, 4, 0, 1],
      segmentLabels: ['P', 'Q', 'R'],
    },
    {
      id: 'midpoint-b3',
      section: 'explore',
      title: 'Trung điểm của đoạn thẳng',
      text: 'Y ở giữa X và Z; XY = YZ = 3 cm. Khi đó Y là trung điểm của đoạn thẳng XZ.\nĐể xác định trung điểm, cần kiểm tra cả hai điều kiện: điểm đó ở giữa hai đầu đoạn thẳng và hai đoạn tạo thành dài bằng nhau.',
      visual: 'segment',
      values: [3, 3, 0, 1],
      segmentLabels: ['X', 'Y', 'Z'],
    },
    {
      id: 'midpoint-b4',
      section: 'explore',
      title: 'Ở giữa nhưng không phải trung điểm',
      text: 'I ở giữa H và K, nhưng HI = 2 cm, IK = 4 cm. Vì HI không bằng IK nên I không phải là trung điểm của HK.',
      visual: 'segment',
      values: [2, 4, 0, 1],
      segmentLabels: ['H', 'I', 'K'],
    },
    {
      id: 'midpoint-b5',
      section: 'explore',
      title: 'Không thẳng hàng thì không ở giữa',
      text: 'Ở hình này, V không nằm trên đường thẳng UW. Vì vậy V không ở giữa U và W và không là trung điểm của UW, dù có thể cách đều U và W.',
      visual: 'segment',
      values: [3, 3, 1, 0],
      segmentLabels: ['U', 'V', 'W'],
    },
    {
      id: 'midpoint-b6',
      section: 'example',
      title: '1. Xác định trung điểm',
      text: 'D ở giữa C và E. Trên hình có CD = 4 cm và DE = 4 cm.\nHai đoạn CD, DE bằng nhau, nên D là trung điểm của CE.',
      visual: 'segment',
      values: [4, 4, 0, 1],
      segmentLabels: ['C', 'D', 'E'],
    },
    {
      id: 'midpoint-b7',
      section: 'example',
      title: '2. Tính độ dài mỗi nửa',
      text: 'PR dài 8 cm, Q là trung điểm của PR.\nĐộ dài đoạn PQ là:\n8 : 2 = 4 (cm).\nVậy PQ = QR = 4 cm.',
      visual: 'none',
      values: [],
    },
    {
      id: 'midpoint-b8',
      section: 'example',
      title: '3. Tính độ dài cả đoạn',
      text: 'H là trung điểm của GI, GH = 3 cm.\nHI = GH = 3 cm.\nĐộ dài đoạn GI là:\n3 + 3 = 6 (cm).\nĐáp số: 6 cm.',
      visual: 'segment',
      values: [3, 3, 0, 1],
      segmentLabels: ['G', 'H', 'I'],
    },
    {
      id: 'midpoint-b9',
      section: 'example',
      title: '4. Cách xác định trung điểm bằng thước',
      text: 'Đoạn RS dài 6 cm. Tính 6 : 2 = 3 cm. Đặt thước dọc theo RS, vạch 0 trùng R; đánh dấu T tại vạch 3 cm. Kiểm tra T ở giữa R, S và RT = TS = 3 cm.\nCó thể gấp một băng giấy sao cho hai đầu trùng nhau; nếp gấp xác định điểm chia băng thành hai phần bằng nhau.',
      visual: 'none',
      values: [],
    },
    {
      id: 'midpoint-b10',
      section: 'guided',
      title: 'Em thử làm',
      text: 'KM dài 10 cm, L là trung điểm của KM. Hai đoạn KL và LM bằng nhau. Hãy tìm độ dài KL.',
      visual: 'none',
      values: [],
    },
  ],
  exercises: [
    {
      id: 'midpoint-e1',
      section: 'foundation',
      kind: 'choice',
      prompt: 'Quan sát hình. Điểm nào ở giữa hai điểm còn lại?',
      answer: 'M',
      hint: 'Xét thứ tự ba điểm trên đoạn thẳng.',
      solution: 'A, M, B thẳng hàng theo thứ tự đó nên M ở giữa A và B.',
      options: ['A', 'M', 'B'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      segment: [2, 4, 0, 0],
      segmentLabels: ['A', 'M', 'B'],
    },
    {
      id: 'midpoint-e2',
      section: 'guided',
      kind: 'number',
      prompt:
        'PR dài 10 cm, Q là trung điểm của PR. Đoạn PQ dài bao nhiêu xăng-ti-mét?',
      answer: '5',
      hint: 'Chia độ dài AB cho 2.',
      solution:
        'Bài giải:\nĐộ dài đoạn PQ là:\n10 : 2 = 5 (cm).\nĐáp số: 5 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'midpoint-e3',
      section: 'practice',
      kind: 'choice',
      prompt: 'Quan sát hình. Y có là trung điểm của XZ không?',
      answer: 'Có',
      hint: 'Kiểm tra điểm ở giữa và hai độ dài.',
      solution: 'Y ở giữa X, Z và XY = YZ = 4 cm nên Y là trung điểm của XZ.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      segment: [4, 4, 0, 1],
      segmentLabels: ['X', 'Y', 'Z'],
    },
    {
      id: 'midpoint-e4',
      section: 'practice',
      kind: 'choice',
      prompt: 'Quan sát hình. I có là trung điểm của HK không?',
      answer: 'Không',
      hint: 'So sánh HI và IK.',
      solution:
        'I ở giữa H, K nhưng HI = 2 cm khác IK = 5 cm nên I không là trung điểm của HK.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      segment: [2, 5, 0, 1],
      segmentLabels: ['H', 'I', 'K'],
    },
    {
      id: 'midpoint-e5',
      section: 'extra',
      kind: 'choice',
      prompt: 'Điểm nào ở giữa P và R trong hình?',
      answer: 'Q',
      hint: 'Nhớ điều kiện điểm ở giữa và trung điểm.',
      solution: 'Q ở giữa P và R.',
      options: ['P', 'Q', 'R'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [2, 5, 0, 0],
      segmentLabels: ['P', 'Q', 'R'],
    },
    {
      id: 'midpoint-e6',
      section: 'extra',
      kind: 'choice',
      prompt: 'Ba điểm C, D, E trong hình có thẳng hàng không?',
      answer: 'Có',
      hint: 'Nhớ điều kiện điểm ở giữa và trung điểm.',
      solution: 'C, D, E cùng nằm trên một đường thẳng.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 5, 0, 0],
      segmentLabels: ['C', 'D', 'E'],
    },
    {
      id: 'midpoint-e7',
      section: 'extra',
      kind: 'choice',
      prompt: 'Điểm V trong hình có ở giữa U và W không?',
      answer: 'Không',
      hint: 'Nhớ điều kiện điểm ở giữa và trung điểm.',
      solution: 'V không nằm trên đường thẳng UW nên không ở giữa U và W.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 3, 1, 0],
      segmentLabels: ['U', 'V', 'W'],
    },
    {
      id: 'midpoint-e8',
      section: 'extra',
      kind: 'choice',
      prompt: 'Q là trung điểm của PR khi nào?',
      answer: 'Q ở giữa P, R và PQ = QR',
      hint: 'Nhớ điều kiện điểm ở giữa và trung điểm.',
      solution: 'Phải có cả hai điều kiện: Q ở giữa P, R và PQ = QR.',
      options: [
        'Q ở giữa P, R và PQ = QR',
        'Chỉ cần Q ở giữa P và R',
        'Chỉ cần PQ = QR',
      ],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e9',
      section: 'extra',
      kind: 'choice',
      prompt: 'Quan sát hình. I có phải là trung điểm của HK không?',
      answer: 'Có',
      hint: 'I đã ở giữa H và K; hãy so sánh hai đoạn.',
      solution:
        'I ở giữa H và K; HI = 2 cm, IK = 2 cm. Hai đoạn bằng nhau nên I là trung điểm của HK.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [2, 2, 0, 1],
      segmentLabels: ['H', 'I', 'K'],
    },
    {
      id: 'midpoint-e10',
      section: 'extra',
      kind: 'choice',
      prompt: 'Quan sát hình. Q có phải là trung điểm của PR không?',
      answer: 'Không',
      hint: 'Q đã ở giữa P và R; hãy so sánh hai đoạn.',
      solution:
        'Q ở giữa P và R; PQ = 2 cm, QR = 4 cm. Hai đoạn không bằng nhau nên Q không là trung điểm của PR.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [2, 4, 0, 1],
      segmentLabels: ['P', 'Q', 'R'],
    },
    {
      id: 'midpoint-e11',
      section: 'extra',
      kind: 'choice',
      prompt: 'Quan sát hình. Y có phải là trung điểm của XZ không?',
      answer: 'Có',
      hint: 'Y đã ở giữa X và Z; hãy so sánh hai đoạn.',
      solution:
        'Y ở giữa X và Z; XY = 5 cm, YZ = 5 cm. Hai đoạn bằng nhau nên Y là trung điểm của XZ.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [5, 5, 0, 1],
      segmentLabels: ['X', 'Y', 'Z'],
    },
    {
      id: 'midpoint-e12',
      section: 'extra',
      kind: 'choice',
      prompt: 'Quan sát hình. D có phải là trung điểm của CE không?',
      answer: 'Không',
      hint: 'D đã ở giữa C và E; hãy so sánh hai đoạn.',
      solution:
        'D ở giữa C và E; CD = 3 cm, DE = 6 cm. Hai đoạn không bằng nhau nên D không là trung điểm của CE.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 6, 0, 1],
      segmentLabels: ['C', 'D', 'E'],
    },
    {
      id: 'midpoint-e13',
      section: 'extra',
      kind: 'number',
      prompt:
        'H là trung điểm của GI, GI = 6 cm. Đoạn HI dài bao nhiêu xăng-ti-mét?',
      answer: '3',
      hint: 'Lấy độ dài GI chia cho 2.',
      solution: 'Bài giải:\nĐộ dài đoạn HI là:\n6 : 2 = 3 (cm).\nĐáp số: 3 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 3, 0, 0],
      segmentLabels: ['G', 'H', 'I'],
    },
    {
      id: 'midpoint-e14',
      section: 'extra',
      kind: 'number',
      prompt:
        'L là trung điểm của KM, KM = 12 cm. Đoạn LM dài bao nhiêu xăng-ti-mét?',
      answer: '6',
      hint: 'Lấy độ dài KM chia cho 2.',
      solution:
        'Bài giải:\nĐộ dài đoạn LM là:\n12 : 2 = 6 (cm).\nĐáp số: 6 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 3, 0, 0],
      segmentLabels: ['K', 'L', 'M'],
    },
    {
      id: 'midpoint-e15',
      section: 'extra',
      kind: 'number',
      prompt:
        'Q là trung điểm của PR, PQ = 4 cm. Đoạn PR dài bao nhiêu xăng-ti-mét?',
      answer: '8',
      hint: 'PR gồm hai đoạn bằng PQ.',
      solution: 'Bài giải:\nĐộ dài đoạn PR là:\n4 × 2 = 8 (cm).\nĐáp số: 8 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 3, 0, 0],
      segmentLabels: ['P', 'Q', 'R'],
    },
    {
      id: 'midpoint-e16',
      section: 'extra',
      kind: 'number',
      prompt:
        'Y là trung điểm của XZ, XY = 7 cm. Đoạn XZ dài bao nhiêu xăng-ti-mét?',
      answer: '14',
      hint: 'XZ gồm hai đoạn bằng XY.',
      solution:
        'Bài giải:\nĐộ dài đoạn XZ là:\n7 × 2 = 14 (cm).\nĐáp số: 14 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'easy',
      workspace: 'medium',
      segment: [3, 3, 0, 0],
      segmentLabels: ['X', 'Y', 'Z'],
    },
    {
      id: 'midpoint-e17',
      section: 'extra',
      kind: 'number',
      prompt:
        'Một băng giấy thẳng dài 16 cm. Lan đánh dấu điểm ở chính giữa để chia băng giấy thành hai phần bằng nhau. Mỗi phần dài bao nhiêu xăng-ti-mét?',
      answer: '8',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution:
        'Bài giải:\nMỗi phần băng giấy dài là:\n16 : 2 = 8 (cm).\nĐáp số: 8 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e18',
      section: 'extra',
      kind: 'number',
      prompt:
        'Một đoạn dây thẳng dài 18 cm. Nam đánh dấu trung điểm của đoạn dây. Khoảng cách từ dấu đó đến mỗi đầu dây là bao nhiêu xăng-ti-mét?',
      answer: '9',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution:
        'Bài giải:\nKhoảng cách từ dấu đến mỗi đầu dây là:\n18 : 2 = 9 (cm).\nĐáp số: 9 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e19',
      section: 'extra',
      kind: 'number',
      prompt:
        'Hai đầu A và B của một thanh gỗ thẳng cách nhau 20 cm. M là trung điểm của AB. Đoạn AM dài bao nhiêu xăng-ti-mét?',
      answer: '10',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution:
        'Bài giải:\nĐộ dài đoạn AM là:\n20 : 2 = 10 (cm).\nĐáp số: 10 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e20',
      section: 'extra',
      kind: 'number',
      prompt:
        'Trên một băng giấy thẳng, M là trung điểm của đoạn AB. Từ A đến M dài 6 cm. Đoạn AB dài bao nhiêu xăng-ti-mét?',
      answer: '12',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution:
        'Bài giải:\nĐộ dài đoạn AB là:\n6 × 2 = 12 (cm).\nĐáp số: 12 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e21',
      section: 'extra',
      kind: 'number',
      prompt:
        'Một sợi dây được căng thẳng từ A đến B. M là trung điểm của AB và MB = 9 cm. Sợi dây AB dài bao nhiêu xăng-ti-mét?',
      answer: '18',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution:
        'Bài giải:\nSợi dây AB dài là:\n9 × 2 = 18 (cm).\nĐáp số: 18 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e22',
      section: 'extra',
      kind: 'number',
      prompt:
        'Trên một cạnh thẳng AB của tấm bìa, M là trung điểm và AM = 5 cm. Đoạn MB dài bao nhiêu xăng-ti-mét?',
      answer: '5',
      hint: 'Trung điểm chia đoạn thẳng thành hai phần bằng nhau.',
      solution: 'Bài giải:\nMB = AM = 5 cm.\nĐáp số: 5 cm.',
      options: [],
      unit: 'cm',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'midpoint-e23',
      section: 'extra',
      kind: 'choice',
      prompt:
        'M cách đều A và B nhưng không nằm trên đường thẳng AB. M có phải là trung điểm của AB không?',
      answer: 'Không',
      hint: 'Cần kiểm tra cả điều kiện ở giữa.',
      solution:
        'M không ở giữa A và B nên không là trung điểm của AB, dù MA = MB.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'challenge',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
      segment: [3, 3, 1, 0],
    },
    {
      id: 'midpoint-e24',
      section: 'extra',
      kind: 'choice',
      prompt:
        'M ở giữa A và B. AM = 3 cm và AB = 8 cm. M có phải là trung điểm của AB không?',
      answer: 'Không',
      hint: 'Tính MB = AB − AM rồi so sánh với AM.',
      solution:
        'MB = 8 − 3 = 5 (cm). AM = 3 cm khác MB = 5 cm nên M không là trung điểm của AB.',
      options: ['Có', 'Không'],
      unit: '',
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'challenge',
      skill: 'Điểm ở giữa và trung điểm',
      difficulty: 'medium',
      workspace: 'medium',
      segment: [3, 5, 0, 0],
    },
  ],
};

export function addMidpointLesson(lessons: MathLessonData[]): MathLessonData[] {
  if (lessons.length >= 100 || lessons.some((l) => l.id === midpointLesson.id))
    return lessons;
  return [...lessons, structuredClone(midpointLesson)];
}
