import type { MathLessonData } from './lessons';

export const multiplicationDivisionLesson: MathLessonData = {
  "id": "math-multiply-divide-components-3",
  "title": "Tìm thành phần trong phép nhân, phép chia",
  "grade": 3,
  "semester": "1",
  "topic": "Số học",
  "goal": "Tìm thừa số, số bị chia, số chia và vận dụng vào bài toán có lời văn.",
  "textbook": "Bài tự biên soạn theo chủ đề Toán 3: tìm thành phần trong phép nhân, phép chia.",
  "teacherNotes": "Các bài tập dùng bảng nhân, chia từ 2 đến 9 và phép chia hết. Cho học sinh gọi tên thành phần chưa biết trước khi tính, rồi thay kết quả vào phép tính để thử lại. Không dùng bài tìm số chia khi thương bằng 0.",
  "knowledgeSummary": "Thừa số × Thừa số = Tích.\nSố bị chia : Số chia = Thương.\nTìm thừa số: lấy tích chia cho thừa số đã biết (khác 0).\nTrong phép chia hết: tìm số bị chia bằng cách lấy thương nhân số chia; tìm số chia bằng cách lấy số bị chia chia cho thương (khác 0).\nVí dụ: □ × 4 = 24 → □ = 6; □ : 4 = 6 → □ = 24; 24 : □ = 6 → □ = 4.\nLưu ý: Không chia cho 0. Thay kết quả vào ô trống để thử lại.",
  "blocks": [
    {
      "id": "muldiv-3-b1",
      "section": "foundation",
      "title": "Tên gọi các thành phần",
      "text": "Trong phép nhân 6 × 4 = 24: 6 và 4 là các thừa số, 24 là tích.\nTrong phép chia 24 : 4 = 6: 24 là số bị chia, 4 là số chia, 6 là thương.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b2",
      "section": "explore",
      "title": "Tìm thừa số",
      "text": "Muốn tìm một thừa số, ta lấy tích chia cho thừa số đã biết (khác 0).\n□ × 4 = 24 hoặc 4 × □ = 24 đều có số cần tìm là 24 : 4 = 6.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b3",
      "section": "explore",
      "title": "Tìm số bị chia",
      "text": "Trong phép chia hết, muốn tìm số bị chia, ta lấy thương nhân với số chia.\n□ : 4 = 6 có số cần tìm là 6 × 4 = 24.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b4",
      "section": "explore",
      "title": "Tìm số chia",
      "text": "Trong phép chia hết có thương khác 0, muốn tìm số chia, ta lấy số bị chia chia cho thương.\n24 : □ = 6 có số cần tìm là 24 : 6 = 4.\nKhông chia cho 0.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b5",
      "section": "example",
      "title": "1. Tìm thừa số",
      "text": "□ × 7 = 42.\nÔ trống là thừa số chưa biết.\nSố cần tìm là: 42 : 7 = 6.\nThử lại: 6 × 7 = 42.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b6",
      "section": "example",
      "title": "2. Tìm số bị chia",
      "text": "□ : 5 = 8.\nÔ trống là số bị chia.\nSố cần tìm là: 8 × 5 = 40.\nThử lại: 40 : 5 = 8.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b7",
      "section": "example",
      "title": "3. Tìm số chia",
      "text": "54 : □ = 6.\nÔ trống là số chia.\nSố cần tìm là: 54 : 6 = 9.\nThử lại: 54 : 9 = 6.",
      "visual": "none",
      "values": []
    },
    {
      "id": "muldiv-3-b8",
      "section": "guided",
      "title": "Em thử làm",
      "text": "Với 8 × □ = 56, hãy gọi tên thành phần chưa biết, chọn phép tính rồi thay kết quả vào ô trống để thử lại.",
      "visual": "none",
      "values": []
    }
  ],
  "exercises": [
    {
      "id": "muldiv-3-e1",
      "section": "foundation",
      "kind": "number",
      "prompt": "Trong phép chia 35 : 5 = 7, số bị chia là số nào?",
      "answer": "35",
      "hint": "Số bị chia đứng trước dấu chia.",
      "solution": "35 là số bị chia; 5 là số chia; 7 là thương.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "muldiv-3-e2",
      "section": "guided",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 8 × □ = 56.",
      "answer": "7",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 56 : 8 = 7.\nThử lại: 8 × 7 = 56.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "muldiv-3-e3",
      "section": "practice",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ : 6 = 9.",
      "answer": "54",
      "hint": "Lấy thương nhân với số chia.",
      "solution": "Số cần tìm là: 9 × 6 = 54.\nThử lại: 54 : 6 = 9.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "muldiv-3-e4",
      "section": "practice",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 48 : □ = 8.",
      "answer": "6",
      "hint": "Lấy số bị chia chia cho thương.",
      "solution": "Số cần tìm là: 48 : 8 = 6.\nThử lại: 48 : 6 = 8.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": []
    },
    {
      "id": "muldiv-3-e5",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ × 3 = 21.",
      "answer": "7",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 21 : 3 = 7.\nThử lại: 7 × 3 = 21.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e6",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 5 × □ = 40.",
      "answer": "8",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 40 : 5 = 8.\nThử lại: 5 × 8 = 40.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e7",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ : 4 = 7.",
      "answer": "28",
      "hint": "Lấy thương nhân với số chia.",
      "solution": "Số cần tìm là: 7 × 4 = 28.\nThử lại: 28 : 4 = 7.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e8",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 36 : □ = 6.",
      "answer": "6",
      "hint": "Lấy số bị chia chia cho thương.",
      "solution": "Số cần tìm là: 36 : 6 = 6.\nThử lại: 36 : 6 = 6.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "foundation",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e9",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ × 6 = 48.",
      "answer": "8",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 48 : 6 = 8.\nThử lại: 8 × 6 = 48.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e10",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 7 × □ = 63.",
      "answer": "9",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 63 : 7 = 9.\nThử lại: 7 × 9 = 63.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e11",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ : 8 = 5.",
      "answer": "40",
      "hint": "Lấy thương nhân với số chia.",
      "solution": "Số cần tìm là: 5 × 8 = 40.\nThử lại: 40 : 8 = 5.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e12",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 56 : □ = 7.",
      "answer": "8",
      "hint": "Lấy số bị chia chia cho thương.",
      "solution": "Số cần tìm là: 56 : 7 = 8.\nThử lại: 56 : 8 = 7.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e13",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ × 9 = 54.",
      "answer": "6",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 54 : 9 = 6.\nThử lại: 6 × 9 = 54.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e14",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 4 × □ = 0.",
      "answer": "0",
      "hint": "Lấy tích chia cho thừa số đã biết.",
      "solution": "Số cần tìm là: 0 : 4 = 0.\nThử lại: 4 × 0 = 0.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e15",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: □ : 9 = 8.",
      "answer": "72",
      "hint": "Lấy thương nhân với số chia.",
      "solution": "Số cần tìm là: 8 × 9 = 72.\nThử lại: 72 : 9 = 8.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e16",
      "section": "extra",
      "kind": "number",
      "prompt": "Tìm số thích hợp điền vào ô trống: 72 : □ = 9.",
      "answer": "8",
      "hint": "Lấy số bị chia chia cho thương.",
      "solution": "Số cần tìm là: 72 : 9 = 8.\nThử lại: 72 : 8 = 9.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e17",
      "section": "extra",
      "kind": "written",
      "prompt": "Điền số thích hợp vào các ô có dấu ? trong bảng phép nhân.",
      "answer": "6; 8; 24; 5; 6",
      "hint": "Mỗi cột là một phép tính. Gọi tên thành phần chưa biết trước khi tính.",
      "solution": "Các số cần điền theo thứ tự cột từ trái sang phải: 6; 8; 24; 5; 6.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium",
      "table": {
        "rows": [
          [
            "Thừa số",
            "?",
            "7",
            "8",
            "?",
            "9"
          ],
          [
            "Thừa số",
            "4",
            "?",
            "3",
            "9",
            "?"
          ],
          [
            "Tích",
            "24",
            "56",
            "?",
            "45",
            "54"
          ]
        ],
        "solution": [
          [
            "Thừa số",
            "6",
            "7",
            "8",
            "5",
            "9"
          ],
          [
            "Thừa số",
            "4",
            "8",
            "3",
            "9",
            "6"
          ],
          [
            "Tích",
            "24",
            "56",
            "24",
            "45",
            "54"
          ]
        ]
      },
      "criteria": [
        "Điền đúng các số còn thiếu và thử lại từng phép tính."
      ]
    },
    {
      "id": "muldiv-3-e18",
      "section": "extra",
      "kind": "written",
      "prompt": "Điền số thích hợp vào các ô có dấu ? trong bảng phép chia.",
      "answer": "36; 6; 9; 40; 8",
      "hint": "Mỗi cột là một phép tính. Gọi tên thành phần chưa biết trước khi tính.",
      "solution": "Các số cần điền theo thứ tự cột từ trái sang phải: 36; 6; 9; 40; 8.",
      "options": [],
      "unit": "",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "skills",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "easy",
      "workspace": "medium",
      "table": {
        "rows": [
          [
            "Số bị chia",
            "?",
            "48",
            "63",
            "?",
            "72"
          ],
          [
            "Số chia",
            "4",
            "?",
            "7",
            "5",
            "?"
          ],
          [
            "Thương",
            "9",
            "8",
            "?",
            "8",
            "9"
          ]
        ],
        "solution": [
          [
            "Số bị chia",
            "36",
            "48",
            "63",
            "40",
            "72"
          ],
          [
            "Số chia",
            "4",
            "6",
            "7",
            "5",
            "8"
          ],
          [
            "Thương",
            "9",
            "8",
            "9",
            "8",
            "9"
          ]
        ]
      },
      "criteria": [
        "Điền đúng các số còn thiếu và thử lại từng phép tính."
      ]
    },
    {
      "id": "muldiv-3-e19",
      "section": "extra",
      "kind": "number",
      "prompt": "Có 6 hộp bút như nhau đựng tất cả 48 chiếc bút. Mỗi hộp có bao nhiêu chiếc bút?",
      "answer": "8",
      "hint": "Số bút mỗi hộp nhân với 6 bằng 48.",
      "solution": "Số bút trong mỗi hộp là:\n48 : 6 = 8 (chiếc).\nĐáp số: 8 chiếc bút.",
      "options": [],
      "unit": "chiếc",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e20",
      "section": "extra",
      "kind": "number",
      "prompt": "Mỗi túi có 7 viên bi. Một số túi như vậy có tất cả 56 viên bi. Có bao nhiêu túi bi?",
      "answer": "8",
      "hint": "7 nhân với số túi bằng 56.",
      "solution": "Số túi bi là:\n56 : 7 = 8 (túi).\nĐáp số: 8 túi bi.",
      "options": [],
      "unit": "túi",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e21",
      "section": "extra",
      "kind": "number",
      "prompt": "Một số chiếc bánh được chia đều vào 5 đĩa, mỗi đĩa có 6 chiếc. Có tất cả bao nhiêu chiếc bánh?",
      "answer": "30",
      "hint": "Tìm số bị chia: lấy số bánh mỗi đĩa nhân với số đĩa.",
      "solution": "Số bánh có tất cả là:\n6 × 5 = 30 (chiếc).\nĐáp số: 30 chiếc bánh.",
      "options": [],
      "unit": "chiếc",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e22",
      "section": "extra",
      "kind": "number",
      "prompt": "Cô giáo chia đều một số quyển vở cho 9 bạn, mỗi bạn được 4 quyển. Cô giáo đã chia bao nhiêu quyển vở?",
      "answer": "36",
      "hint": "Số vở ban đầu chia cho 9 bằng 4.",
      "solution": "Số vở cô giáo đã chia là:\n4 × 9 = 36 (quyển).\nĐáp số: 36 quyển vở.",
      "options": [],
      "unit": "quyển",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e23",
      "section": "extra",
      "kind": "number",
      "prompt": "Có 42 học sinh được chia đều thành các nhóm, mỗi nhóm có 7 học sinh. Có bao nhiêu nhóm?",
      "answer": "6",
      "hint": "42 chia cho số nhóm bằng 7.",
      "solution": "Số nhóm là:\n42 : 7 = 6 (nhóm).\nĐáp số: 6 nhóm.",
      "options": [],
      "unit": "nhóm",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    },
    {
      "id": "muldiv-3-e24",
      "section": "extra",
      "kind": "number",
      "prompt": "Có 64 quả cam được chia đều vào các rổ, mỗi rổ có 8 quả. Có bao nhiêu rổ cam?",
      "answer": "8",
      "hint": "Tìm số chia: lấy 64 chia cho 8.",
      "solution": "Số rổ cam là:\n64 : 8 = 8 (rổ).\nĐáp số: 8 rổ cam.",
      "options": [],
      "unit": "rổ",
      "simplified": false,
      "tolerance": 0,
      "mistakes": [],
      "group": "application",
      "skill": "Tìm thành phần trong phép nhân, phép chia",
      "difficulty": "medium",
      "workspace": "medium"
    }
  ]
};

export function addMultiplicationDivisionLesson(lessons: MathLessonData[]): MathLessonData[] {
  if (lessons.length >= 100 || lessons.some(lesson => lesson.id === multiplicationDivisionLesson.id)) return lessons;
  const next = [...lessons];
  const index = next.findIndex(lesson => lesson.id === 'math-add-subtract-components-3');
  next.splice(index < 0 ? next.length : index + 1, 0, structuredClone(multiplicationDivisionLesson));
  return next;
}
