import { MathLessonData } from './lessons';

export const primaryFractionLessons: MathLessonData[] = [
  {
    "id": "math-fraction-intro-4",
    "title": "Làm quen với phân số và rút gọn",
    "grade": 4,
    "topic": "Phân số",
    "goal": "Đọc, viết phân số; nhận biết tử và mẫu; tạo phân số bằng nhau và rút gọn.",
    "textbook": "Bài tự biên soạn theo phạm vi phân số lớp 4 của chương trình GDPT 2018; chưa gắn với trang sách cụ thể.",
    "teacherNotes": "Dùng số tự nhiên, mẫu số khác 0. Không yêu cầu kiến thức số nguyên âm, ƯCLN hay BCNN. Học theo thứ tự: làm quen; quy đồng và so sánh; cộng trừ; nhân chia; tìm phân số của một số.",
    "knowledgeSummary": "Phân số: Chia một đơn vị thành các phần bằng nhau. Mẫu số cho biết số phần bằng nhau; tử số cho biết số phần được lấy. Tử số là số tự nhiên, mẫu số là số tự nhiên khác 0.\nTính chất và rút gọn: Nhân cả tử và mẫu với cùng một số tự nhiên khác 0 được phân số bằng phân số đã cho. Có thể chia cả tử và mẫu cho cùng một số tự nhiên khác 0 nếu cả hai đều chia hết cho số đó.\nVí dụ: Chia hình thành 4 phần bằng nhau, tô màu 3 phần: phần tô màu là 3/4 hình.\nLưu ý: Mẫu số khác 0; chia hình thành các phần bằng nhau.",
    "blocks": [
      {
        "id": "math-fraction-intro-4-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ôn bảng nhân, bảng chia và cách chia một hình thành các phần bằng nhau.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-intro-4-k0",
        "section": "explore",
        "title": "Phân số",
        "text": "Chia một đơn vị thành các phần bằng nhau. Mẫu số cho biết số phần bằng nhau; tử số cho biết số phần được lấy. Tử số là số tự nhiên, mẫu số là số tự nhiên khác 0.",
        "visual": "fractions",
        "values": [
          3,
          4,
          3,
          4
        ]
      },
      {
        "id": "math-fraction-intro-4-k1",
        "section": "explore",
        "title": "Tính chất và rút gọn",
        "text": "Nhân cả tử và mẫu với cùng một số tự nhiên khác 0 được phân số bằng phân số đã cho. Có thể chia cả tử và mẫu cho cùng một số tự nhiên khác 0 nếu cả hai đều chia hết cho số đó.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-intro-4-ex0",
        "section": "example",
        "title": "1. Nhìn hình và viết",
        "text": "Chia hình thành 4 phần bằng nhau, tô màu 3 phần: phần tô màu là 3/4 hình.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-intro-4-ex1",
        "section": "example",
        "title": "2. Rút gọn",
        "text": "6/8 = (6 : 2)/(8 : 2) = 3/4.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-intro-4-guided",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Đọc, viết phân số; nhận biết tử và mẫu; tạo phân số bằng nhau và rút gọn.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Một hình chia thành 5 phần bằng nhau, tô màu 3 phần. Viết phân số chỉ phần tô màu.",
        "answer": "3/5",
        "hint": "Số phần tô màu là tử số, tổng số phần bằng nhau là mẫu số.",
        "solution": "Phần tô màu chiếm 3/5 hình.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q1",
        "section": "foundation",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tử số của 2/5 là bao nhiêu?",
        "answer": "2",
        "hint": "Tử số viết trên gạch ngang.",
        "solution": "Tử số là 2.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q2",
        "section": "guided",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Rút gọn 4/6.",
        "answer": "2/3",
        "hint": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1.",
        "solution": "4/6 = (4 : 2)/(6 : 2) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Điền số vào ô trống: 1/3 = □/6.",
        "answer": "2",
        "hint": "Mẫu số đã nhân với 2.",
        "solution": "1/3 = (1 × 2)/(3 × 2) = 2/6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Một hình chia thành 5 phần bằng nhau, tô màu 3 phần. Viết phân số chỉ phần tô màu.",
        "answer": "3/5",
        "hint": "Số phần tô màu là tử số, tổng số phần bằng nhau là mẫu số.",
        "solution": "Phần tô màu chiếm 3/5 hình.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q5",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Một hình chia thành 7 phần bằng nhau, tô màu 2 phần. Viết phân số chỉ phần tô màu.",
        "answer": "2/7",
        "hint": "Số phần tô màu là tử số, tổng số phần bằng nhau là mẫu số.",
        "solution": "Phần tô màu chiếm 2/7 hình.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q6",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Một hình chia thành 8 phần bằng nhau, tô màu 5 phần. Viết phân số chỉ phần tô màu.",
        "answer": "5/8",
        "hint": "Số phần tô màu là tử số, tổng số phần bằng nhau là mẫu số.",
        "solution": "Phần tô màu chiếm 5/8 hình.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q7",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Một hình chia thành 9 phần bằng nhau, tô màu 4 phần. Viết phân số chỉ phần tô màu.",
        "answer": "4/9",
        "hint": "Số phần tô màu là tử số, tổng số phần bằng nhau là mẫu số.",
        "solution": "Phần tô màu chiếm 4/9 hình.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q8",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tử số của 2/5 là bao nhiêu?",
        "answer": "2",
        "hint": "Tử số viết trên gạch ngang.",
        "solution": "Tử số là 2.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q9",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Mẫu số của 2/5 là bao nhiêu?",
        "answer": "5",
        "hint": "Mẫu số viết dưới gạch ngang.",
        "solution": "Mẫu số là 5.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q10",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tử số của 4/7 là bao nhiêu?",
        "answer": "4",
        "hint": "Tử số viết trên gạch ngang.",
        "solution": "Tử số là 4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q11",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Mẫu số của 4/7 là bao nhiêu?",
        "answer": "7",
        "hint": "Mẫu số viết dưới gạch ngang.",
        "solution": "Mẫu số là 7.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q12",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 4/6.",
        "answer": "2/3",
        "hint": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1.",
        "solution": "4/6 = (4 : 2)/(6 : 2) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 6/8.",
        "answer": "3/4",
        "hint": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1.",
        "solution": "6/8 = (6 : 2)/(8 : 2) = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q14",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 8/12.",
        "answer": "2/3",
        "hint": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1.",
        "solution": "8/12 = (8 : 4)/(12 : 4) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q15",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Rút gọn 10/15.",
        "answer": "2/3",
        "hint": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1.",
        "solution": "10/15 = (10 : 5)/(15 : 5) = 2/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q16",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số vào ô trống: 1/3 = □/6.",
        "answer": "2",
        "hint": "Mẫu số đã nhân với 2.",
        "solution": "1/3 = (1 × 2)/(3 × 2) = 2/6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số vào ô trống: 2/5 = □/15.",
        "answer": "6",
        "hint": "Mẫu số đã nhân với 3.",
        "solution": "2/5 = (2 × 3)/(5 × 3) = 6/15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số vào ô trống: 3/4 = □/8.",
        "answer": "6",
        "hint": "Mẫu số đã nhân với 2.",
        "solution": "3/4 = (3 × 2)/(4 × 2) = 6/8.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số vào ô trống: 2/7 = □/28.",
        "answer": "8",
        "hint": "Mẫu số đã nhân với 4.",
        "solution": "2/7 = (2 × 4)/(7 × 4) = 8/28.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 8 miếng bánh bằng nhau, ăn 3 miếng. Đã ăn bao nhiêu phần chiếc bánh?",
        "answer": "3/8",
        "hint": "Viết số miếng đã ăn trên tổng số miếng.",
        "solution": "Đã ăn 3/8 chiếc bánh.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q21",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Một băng giấy chia thành 10 phần bằng nhau, tô màu 4 phần. Viết phân số tối giản chỉ phần tô màu.",
        "answer": "2/5",
        "hint": "Rút gọn 4/10.",
        "solution": "4/10 = (4 : 2)/(10 : 2) = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-intro-4-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Phân số nào bằng 1?",
        "answer": "7/7",
        "hint": "Tử số bằng mẫu số.",
        "solution": "7/7 = 1.",
        "options": [
          "7/7",
          "1/7",
          "7/8"
        ],
        "kind": "choice",
        "id": "math-fraction-intro-4-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số vào ô trống: □/12 = 3/4.",
        "answer": "9",
        "hint": "12 = 4 × 3.",
        "solution": "3/4 = (3 × 3)/(4 × 3) = 9/12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-intro-4-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Làm quen với phân số và rút gọn",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-compare-4",
    "title": "Quy đồng và so sánh phân số",
    "grade": 4,
    "topic": "Phân số",
    "goal": "Quy đồng và so sánh khi cùng mẫu hoặc một mẫu chia hết cho mẫu còn lại.",
    "textbook": "Bài tự biên soạn theo phạm vi phân số lớp 4 của chương trình GDPT 2018; chưa gắn với trang sách cụ thể.",
    "teacherNotes": "Dùng số tự nhiên, mẫu số khác 0. Không yêu cầu kiến thức số nguyên âm, ƯCLN hay BCNN. Học theo thứ tự: làm quen; quy đồng và so sánh; cộng trừ; nhân chia; tìm phân số của một số.",
    "knowledgeSummary": "Quy đồng: Khi một mẫu số chia hết cho mẫu số còn lại, chọn mẫu lớn làm mẫu chung. Nhân cả tử và mẫu của phân số kia với số thích hợp.\nSo sánh: Cùng mẫu: phân số có tử lớn hơn thì lớn hơn. Khác mẫu: quy đồng rồi so sánh. Tử nhỏ hơn mẫu thì phân số nhỏ hơn 1; tử bằng mẫu thì phân số bằng 1.\nVí dụ: So sánh 2/3 và 5/6. Vì 6 : 3 = 2 nên 2/3 = (2 × 2)/(3 × 2) = 4/6.\nLưu ý: Mẫu số khác 0; chia hình thành các phần bằng nhau.",
    "blocks": [
      {
        "id": "math-fraction-compare-4-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ôn bảng nhân, bảng chia và cách chia một hình thành các phần bằng nhau.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-4-k0",
        "section": "explore",
        "title": "Quy đồng",
        "text": "Khi một mẫu số chia hết cho mẫu số còn lại, chọn mẫu lớn làm mẫu chung. Nhân cả tử và mẫu của phân số kia với số thích hợp.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-4-k1",
        "section": "explore",
        "title": "So sánh",
        "text": "Cùng mẫu: phân số có tử lớn hơn thì lớn hơn. Khác mẫu: quy đồng rồi so sánh. Tử nhỏ hơn mẫu thì phân số nhỏ hơn 1; tử bằng mẫu thì phân số bằng 1.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-4-ex0",
        "section": "example",
        "title": "1. Chọn mẫu chung",
        "text": "So sánh 2/3 và 5/6. Vì 6 : 3 = 2 nên 2/3 = (2 × 2)/(3 × 2) = 4/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-4-ex1",
        "section": "example",
        "title": "2. So sánh tử",
        "text": "4 < 5 nên 4/6 < 5/6. Vậy 2/3 < 5/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-compare-4-guided",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Quy đồng và so sánh khi cùng mẫu hoặc một mẫu chia hết cho mẫu còn lại.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Quy đồng 1/2 về mẫu 4. Tử số mới là bao nhiêu?",
        "answer": "2",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "1/2 = (1 × 2)/(2 × 2) = 2/4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q1",
        "section": "foundation",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Quy đồng 2/5 về mẫu 15. Tử số mới là bao nhiêu?",
        "answer": "6",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "2/5 = (2 × 3)/(5 × 3) = 6/15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q2",
        "section": "guided",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "So sánh 1/4 và 3/4.",
        "answer": "1/4 < 3/4",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "1/4 = 1/4; 3/4 = 3/4. Vậy 1/4 < 3/4.",
        "options": [
          "1/4 < 3/4",
          "1/4 > 3/4",
          "1/4 = 3/4"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q3",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "So sánh 5/6 và 1/2.",
        "answer": "5/6 > 1/2",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "5/6 = 5/6; 1/2 = 3/6. Vậy 5/6 > 1/2.",
        "options": [
          "5/6 < 1/2",
          "5/6 > 1/2",
          "5/6 = 1/2"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Quy đồng 1/2 về mẫu 4. Tử số mới là bao nhiêu?",
        "answer": "2",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "1/2 = (1 × 2)/(2 × 2) = 2/4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q5",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 2/3 về mẫu 6. Tử số mới là bao nhiêu?",
        "answer": "4",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "2/3 = (2 × 2)/(3 × 2) = 4/6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q6",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 3/4 về mẫu 8. Tử số mới là bao nhiêu?",
        "answer": "6",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "3/4 = (3 × 2)/(4 × 2) = 6/8.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q7",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 1/5 về mẫu 10. Tử số mới là bao nhiêu?",
        "answer": "2",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "1/5 = (1 × 2)/(5 × 2) = 2/10.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q8",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 2/5 về mẫu 15. Tử số mới là bao nhiêu?",
        "answer": "6",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "2/5 = (2 × 3)/(5 × 3) = 6/15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q9",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 3/7 về mẫu 14. Tử số mới là bao nhiêu?",
        "answer": "6",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "3/7 = (3 × 2)/(7 × 2) = 6/14.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q10",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 5/6 về mẫu 18. Tử số mới là bao nhiêu?",
        "answer": "15",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "5/6 = (5 × 3)/(6 × 3) = 15/18.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q11",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Quy đồng 1/3 về mẫu 12. Tử số mới là bao nhiêu?",
        "answer": "4",
        "hint": "Lấy mẫu mới chia mẫu cũ để tìm số cần nhân.",
        "solution": "1/3 = (1 × 4)/(3 × 4) = 4/12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q12",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 1/4 và 3/4.",
        "answer": "1/4 < 3/4",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "1/4 = 1/4; 3/4 = 3/4. Vậy 1/4 < 3/4.",
        "options": [
          "1/4 < 3/4",
          "1/4 > 3/4",
          "1/4 = 3/4"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q13",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 2/3 và 3/6.",
        "answer": "2/3 > 3/6",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "2/3 = 4/6; 3/6 = 3/6. Vậy 2/3 > 3/6.",
        "options": [
          "2/3 < 3/6",
          "2/3 > 3/6",
          "2/3 = 3/6"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q14",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 3/4 và 5/8.",
        "answer": "3/4 > 5/8",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "3/4 = 6/8; 5/8 = 5/8. Vậy 3/4 > 5/8.",
        "options": [
          "3/4 < 5/8",
          "3/4 > 5/8",
          "3/4 = 5/8"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q15",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 2/5 và 4/10.",
        "answer": "2/5 = 4/10",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "2/5 = 4/10; 4/10 = 4/10. Vậy 2/5 = 4/10.",
        "options": [
          "2/5 < 4/10",
          "2/5 > 4/10",
          "2/5 = 4/10"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q16",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 5/6 và 1/2.",
        "answer": "5/6 > 1/2",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "5/6 = 5/6; 1/2 = 3/6. Vậy 5/6 > 1/2.",
        "options": [
          "5/6 < 1/2",
          "5/6 > 1/2",
          "5/6 = 1/2"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 3/10 và 2/5.",
        "answer": "3/10 < 2/5",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "3/10 = 3/10; 2/5 = 4/10. Vậy 3/10 < 2/5.",
        "options": [
          "3/10 < 2/5",
          "3/10 > 2/5",
          "3/10 = 2/5"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 4/7 và 6/7.",
        "answer": "4/7 < 6/7",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "4/7 = 4/7; 6/7 = 6/7. Vậy 4/7 < 6/7.",
        "options": [
          "4/7 < 6/7",
          "4/7 > 6/7",
          "4/7 = 6/7"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "So sánh 1/3 và 3/9.",
        "answer": "1/3 = 3/9",
        "hint": "Nếu khác mẫu, chọn mẫu lớn làm mẫu chung.",
        "solution": "1/3 = 3/9; 3/9 = 3/9. Vậy 1/3 = 3/9.",
        "options": [
          "1/3 < 3/9",
          "1/3 > 3/9",
          "1/3 = 3/9"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Mai ăn 1/2 chiếc bánh, Nam ăn 3/4 chiếc bánh cùng loại và cùng kích thước. Ai ăn nhiều hơn?",
        "answer": "Nam",
        "hint": "Đổi 1/2 thành phân số có mẫu 4.",
        "solution": "1/2 = 2/4 < 3/4 nên Nam ăn nhiều hơn.",
        "options": [
          "Mai",
          "Nam",
          "Bằng nhau"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q21",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Chọn phân số lớn nhất.",
        "answer": "7/8",
        "hint": "Đưa về mẫu 8.",
        "solution": "1/2 = 4/8; 3/4 = 6/8. Lớn nhất là 7/8.",
        "options": [
          "1/2",
          "3/4",
          "7/8"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q22",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Chọn dãy phân số theo thứ tự tăng dần.",
        "answer": "1/4 < 1/2 < 3/4",
        "hint": "Đưa về mẫu 4.",
        "solution": "1/4 < 2/4 < 3/4.",
        "options": [
          "1/4 < 1/2 < 3/4",
          "1/2 < 1/4 < 3/4",
          "3/4 < 1/2 < 1/4"
        ],
        "kind": "choice",
        "id": "math-fraction-compare-4-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Điền số tự nhiên vào ô trống: 2/7 < □/7 < 4/7.",
        "answer": "3",
        "hint": "So sánh các tử số.",
        "solution": "2 < 3 < 4 nên số cần điền là 3.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-compare-4-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Quy đồng và so sánh phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-add-subtract-4",
    "title": "Cộng và trừ phân số",
    "grade": 4,
    "topic": "Phân số",
    "goal": "Cộng, trừ phân số cùng mẫu hoặc một mẫu chia hết cho mẫu còn lại.",
    "textbook": "Bài tự biên soạn theo phạm vi phân số lớp 4 của chương trình GDPT 2018; chưa gắn với trang sách cụ thể.",
    "teacherNotes": "Dùng số tự nhiên, mẫu số khác 0. Không yêu cầu kiến thức số nguyên âm, ƯCLN hay BCNN. Học theo thứ tự: làm quen; quy đồng và so sánh; cộng trừ; nhân chia; tìm phân số của một số.",
    "knowledgeSummary": "Cùng mẫu: Cộng hoặc trừ các tử số, giữ nguyên mẫu số. Trong bài này, phép trừ có số bị trừ không nhỏ hơn số trừ.\nKhác mẫu: Nếu một mẫu chia hết cho mẫu kia, quy đồng về mẫu lớn rồi tính. Rút gọn kết quả khi có thể.\nVí dụ: 1/2 + 1/4 = 2/4 + 1/4 = 3/4.\nLưu ý: Mẫu số khác 0; chia hình thành các phần bằng nhau.",
    "blocks": [
      {
        "id": "math-fraction-add-subtract-4-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ôn bảng nhân, bảng chia và cách chia một hình thành các phần bằng nhau.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-add-subtract-4-k0",
        "section": "explore",
        "title": "Cùng mẫu",
        "text": "Cộng hoặc trừ các tử số, giữ nguyên mẫu số. Trong bài này, phép trừ có số bị trừ không nhỏ hơn số trừ.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-add-subtract-4-k1",
        "section": "explore",
        "title": "Khác mẫu",
        "text": "Nếu một mẫu chia hết cho mẫu kia, quy đồng về mẫu lớn rồi tính. Rút gọn kết quả khi có thể.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-add-subtract-4-ex0",
        "section": "example",
        "title": "1. Cộng",
        "text": "1/2 + 1/4 = 2/4 + 1/4 = 3/4.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-add-subtract-4-ex1",
        "section": "example",
        "title": "2. Trừ",
        "text": "5/6 − 1/3 = 5/6 − 2/6 = 3/6 = 1/2.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-add-subtract-4-guided",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Cộng, trừ phân số cùng mẫu hoặc một mẫu chia hết cho mẫu còn lại.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tính 1/5 + 2/5.",
        "answer": "3/5",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/5 + 2/5 = 3/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q1",
        "section": "foundation",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 1/2 + 1/4.",
        "answer": "3/4",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/2 + 1/4 = 2/4 + 1/4 = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q2",
        "section": "guided",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 2/3 + 1/6.",
        "answer": "5/6",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "2/3 + 1/6 = 4/6 + 1/6 = 5/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 1/3 + 2/9.",
        "answer": "5/9",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/3 + 2/9 = 3/9 + 2/9 = 5/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q4",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 1/5 + 2/5.",
        "answer": "3/5",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/5 + 2/5 = 3/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q5",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Cộng và trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/5 − 1/5.",
        "answer": "1/5",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "2/5 − 1/5 = 1/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q6",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Cộng và trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/7 + 1/7.",
        "answer": "4/7",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "3/7 + 1/7 = 4/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q7",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Cộng và trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/7 − 1/7.",
        "answer": "2/7",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "3/7 − 1/7 = 2/7.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q8",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Cộng và trừ phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/2 + 1/4.",
        "answer": "3/4",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/2 + 1/4 = 2/4 + 1/4 = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q9",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/2 − 1/4.",
        "answer": "1/4",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/2 − 1/4 = 2/4 − 1/4 = 1/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q10",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/4 + 1/8.",
        "answer": "7/8",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "3/4 + 1/8 = 6/8 + 1/8 = 7/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q11",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/4 − 1/8.",
        "answer": "5/8",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "3/4 − 1/8 = 6/8 − 1/8 = 5/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q12",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/3 + 1/6.",
        "answer": "5/6",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "2/3 + 1/6 = 4/6 + 1/6 = 5/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/3 − 1/6.",
        "answer": "1/2",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "2/3 − 1/6 = 4/6 − 1/6 = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q14",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 7/10 + 1/5.",
        "answer": "9/10",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "7/10 + 1/5 = 7/10 + 2/10 = 9/10.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q15",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 7/10 − 1/5.",
        "answer": "1/2",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "7/10 − 1/5 = 7/10 − 2/10 = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q16",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/3 + 2/9.",
        "answer": "5/9",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/3 + 2/9 = 3/9 + 2/9 = 5/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q17",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/3 − 2/9.",
        "answer": "1/9",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/3 − 2/9 = 3/9 − 2/9 = 1/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q18",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/6 + 1/2.",
        "answer": "4/3",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "5/6 + 1/2 = 5/6 + 3/6 = 4/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q19",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/6 − 1/2.",
        "answer": "1/3",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "5/6 − 1/2 = 5/6 − 3/6 = 1/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q20",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/1 + 2/5.",
        "answer": "7/5",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/1 + 2/5 = 5/5 + 2/5 = 7/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q21",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/1 − 2/5.",
        "answer": "3/5",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "1/1 − 2/5 = 5/5 − 2/5 = 3/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Cộng và trừ phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 0/1 + 3/8.",
        "answer": "3/8",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "0/1 + 3/8 = 0/8 + 3/8 = 3/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q23",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Cộng và trừ phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/8 − 0/1.",
        "answer": "3/8",
        "hint": "Quy đồng nếu cần, rồi tính với các tử và giữ mẫu.",
        "solution": "3/8 − 0/1 = 3/8 − 0/8 = 3/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-add-subtract-4-q24",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Cộng và trừ phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-multiply-divide-4",
    "title": "Nhân và chia phân số",
    "grade": 4,
    "topic": "Phân số",
    "goal": "Nhân hai phân số; chia bằng cách đảo phân số thứ hai rồi nhân.",
    "textbook": "Bài tự biên soạn theo phạm vi phân số lớp 4 của chương trình GDPT 2018; chưa gắn với trang sách cụ thể.",
    "teacherNotes": "Dùng số tự nhiên, mẫu số khác 0. Không yêu cầu kiến thức số nguyên âm, ƯCLN hay BCNN. Học theo thứ tự: làm quen; quy đồng và so sánh; cộng trừ; nhân chia; tìm phân số của một số.",
    "knowledgeSummary": "Nhân phân số: Nhân tử số với tử số, mẫu số với mẫu số rồi rút gọn.\nChia phân số: Giữ nguyên phân số thứ nhất, đảo tử và mẫu của phân số thứ hai rồi nhân. Phân số thứ hai phải khác 0.\nVí dụ: 2/3 × 3/4 = (2 × 3)/(3 × 4) = 6/12 = 1/2.\nLưu ý: Mẫu số khác 0; chia hình thành các phần bằng nhau.",
    "blocks": [
      {
        "id": "math-fraction-multiply-divide-4-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ôn bảng nhân, bảng chia và cách chia một hình thành các phần bằng nhau.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-divide-4-k0",
        "section": "explore",
        "title": "Nhân phân số",
        "text": "Nhân tử số với tử số, mẫu số với mẫu số rồi rút gọn.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-divide-4-k1",
        "section": "explore",
        "title": "Chia phân số",
        "text": "Giữ nguyên phân số thứ nhất, đảo tử và mẫu của phân số thứ hai rồi nhân. Phân số thứ hai phải khác 0.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-divide-4-ex0",
        "section": "example",
        "title": "1. Nhân",
        "text": "2/3 × 3/4 = (2 × 3)/(3 × 4) = 6/12 = 1/2.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-divide-4-ex1",
        "section": "example",
        "title": "2. Chia",
        "text": "2/3 : 4/5 = 2/3 × 5/4 = 10/12 = 5/6.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-multiply-divide-4-guided",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Nhân hai phân số; chia bằng cách đảo phân số thứ hai rồi nhân.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tính 1/2 × 2/3.",
        "answer": "1/3",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/2 × 2/3 = (1 × 2)/(2 × 3) = 2/6 = 1/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q1",
        "section": "foundation",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 3/7 × 7/9.",
        "answer": "1/3",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "3/7 × 7/9 = (3 × 7)/(7 × 9) = 21/63 = 1/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q2",
        "section": "guided",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 2/3 × 1/6.",
        "answer": "1/9",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/3 × 1/6 = (2 × 1)/(3 × 6) = 2/18 = 1/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q3",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 1/5 × 1/2.",
        "answer": "1/10",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/5 × 1/2 = (1 × 1)/(5 × 2) = 1/10 = 1/10.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q4",
        "section": "practice",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tính 1/2 × 2/3.",
        "answer": "1/3",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/2 × 2/3 = (1 × 2)/(2 × 3) = 2/6 = 1/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q5",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Nhân và chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/2 : 2/3.",
        "answer": "3/4",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/2 : 2/3 = 1/2 × 3/2 = (1 × 3)/(2 × 2) = 3/4 = 3/4.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q6",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Nhân và chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/5 × 3/4.",
        "answer": "3/10",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/5 × 3/4 = (2 × 3)/(5 × 4) = 6/20 = 3/10.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q7",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Nhân và chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/5 : 3/4.",
        "answer": "8/15",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/5 : 3/4 = 2/5 × 4/3 = (2 × 4)/(5 × 3) = 8/15 = 8/15.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q8",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Nhân và chia phân số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/7 × 7/9.",
        "answer": "1/3",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "3/7 × 7/9 = (3 × 7)/(7 × 9) = 21/63 = 1/3.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q9",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/7 : 7/9.",
        "answer": "27/49",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "3/7 : 7/9 = 3/7 × 9/7 = (3 × 9)/(7 × 7) = 27/49 = 27/49.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q10",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/8 × 4/5.",
        "answer": "1/2",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "5/8 × 4/5 = (5 × 4)/(8 × 5) = 20/40 = 1/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q11",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/8 : 4/5.",
        "answer": "25/32",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "5/8 : 4/5 = 5/8 × 5/4 = (5 × 5)/(8 × 4) = 25/32 = 25/32.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q12",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/3 × 1/6.",
        "answer": "1/9",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/3 × 1/6 = (2 × 1)/(3 × 6) = 2/18 = 1/9.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q13",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/3 : 1/6.",
        "answer": "4",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/3 : 1/6 = 2/3 × 6/1 = (2 × 6)/(3 × 1) = 12/3 = 4.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-multiply-divide-4-q14",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/4 × 2/1.",
        "answer": "3/2",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "3/4 × 2/1 = (3 × 2)/(4 × 1) = 6/4 = 3/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q15",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 3/4 : 2/1.",
        "answer": "3/8",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "3/4 : 2/1 = 3/4 × 1/2 = (3 × 1)/(4 × 2) = 3/8 = 3/8.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q16",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/5 × 1/2.",
        "answer": "1/10",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/5 × 1/2 = (1 × 1)/(5 × 2) = 1/10 = 1/10.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q17",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 1/5 : 1/2.",
        "answer": "2/5",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "1/5 : 1/2 = 1/5 × 2/1 = (1 × 2)/(5 × 1) = 2/5 = 2/5.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q18",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 4/9 × 3/8.",
        "answer": "1/6",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "4/9 × 3/8 = (4 × 3)/(9 × 8) = 12/72 = 1/6.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q19",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 4/9 : 3/8.",
        "answer": "32/27",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "4/9 : 3/8 = 4/9 × 8/3 = (4 × 8)/(9 × 3) = 32/27 = 32/27.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q20",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/6 × 1/3.",
        "answer": "5/18",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "5/6 × 1/3 = (5 × 1)/(6 × 3) = 5/18 = 5/18.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q21",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 5/6 : 1/3.",
        "answer": "5/2",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "5/6 : 1/3 = 5/6 × 3/1 = (5 × 3)/(6 × 1) = 15/6 = 5/2.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q22",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Nhân và chia phân số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/7 × 3/5.",
        "answer": "6/35",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/7 × 3/5 = (2 × 3)/(7 × 5) = 6/35 = 6/35.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q23",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Nhân và chia phân số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Tính 2/7 : 3/5.",
        "answer": "10/21",
        "hint": "Nhân tử với tử, mẫu với mẫu. Với phép chia, đảo phân số thứ hai rồi nhân.",
        "solution": "2/7 : 3/5 = 2/7 × 5/3 = (2 × 5)/(7 × 3) = 10/21 = 10/21.",
        "options": [],
        "kind": "fraction",
        "id": "math-fraction-multiply-divide-4-q24",
        "section": "extra",
        "unit": "",
        "simplified": true,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Nhân và chia phân số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  },
  {
    "id": "math-fraction-of-number-4",
    "title": "Tìm phân số của một số",
    "grade": 4,
    "topic": "Phân số",
    "goal": "Tìm một phần của số lượng đã biết và giải bài toán có lời văn.",
    "textbook": "Bài tự biên soạn theo phạm vi phân số lớp 4 của chương trình GDPT 2018; chưa gắn với trang sách cụ thể.",
    "teacherNotes": "Dùng số tự nhiên, mẫu số khác 0. Không yêu cầu kiến thức số nguyên âm, ƯCLN hay BCNN. Học theo thứ tự: làm quen; quy đồng và so sánh; cộng trừ; nhân chia; tìm phân số của một số.",
    "knowledgeSummary": "Cách tính: Muốn tìm một phân số của một số, lấy số đó nhân với phân số. Có thể chia số đó cho mẫu rồi nhân với tử khi phép chia thực hiện thuận tiện.\nĐọc đề: Xác định số lượng ban đầu và phân số cần lấy. Nếu hỏi phần còn lại, tính phần đã lấy rồi trừ khỏi số lượng ban đầu.\nVí dụ: Tìm 3/4 của 20: 20 × (3/4) = 20 : 4 × 3 = 15.\nLưu ý: Mẫu số khác 0; chia hình thành các phần bằng nhau.",
    "blocks": [
      {
        "id": "math-fraction-of-number-4-pre",
        "section": "foundation",
        "title": "Em cần biết gì trước?",
        "text": "Ôn bảng nhân, bảng chia và cách chia một hình thành các phần bằng nhau.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-of-number-4-k0",
        "section": "explore",
        "title": "Cách tính",
        "text": "Muốn tìm một phân số của một số, lấy số đó nhân với phân số. Có thể chia số đó cho mẫu rồi nhân với tử khi phép chia thực hiện thuận tiện.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-of-number-4-k1",
        "section": "explore",
        "title": "Đọc đề",
        "text": "Xác định số lượng ban đầu và phân số cần lấy. Nếu hỏi phần còn lại, tính phần đã lấy rồi trừ khỏi số lượng ban đầu.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-of-number-4-ex0",
        "section": "example",
        "title": "1. Tìm một phần",
        "text": "Tìm 3/4 của 20: 20 × (3/4) = 20 : 4 × 3 = 15.",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-of-number-4-ex1",
        "section": "example",
        "title": "2. Tính phần còn lại",
        "text": "Có 24 quả, bán 1/3 số quả. Số đã bán: 24 × (1/3) = 8 (quả). Số còn lại: 24 − 8 = 16 (quả).",
        "visual": "none",
        "values": []
      },
      {
        "id": "math-fraction-of-number-4-guided",
        "section": "guided",
        "title": "Em thử làm",
        "text": "Tìm một phần của số lượng đã biết và giải bài toán có lời văn.",
        "visual": "none",
        "values": []
      }
    ],
    "exercises": [
      {
        "prompt": "Tìm 1/2 của 12.",
        "answer": "6",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "12 × (1/2) = 12 : 2 × 1 = 6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q1",
        "section": "foundation",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm 2/3 của 18.",
        "answer": "12",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "18 × (2/3) = 18 : 3 × 2 = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q2",
        "section": "guided",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm 3/8 của 40.",
        "answer": "15",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "40 × (3/8) = 40 : 8 × 3 = 15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q3",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Lớp có 36 học sinh, 2/3 số học sinh tham gia câu lạc bộ. Có bao nhiêu học sinh tham gia?",
        "answer": "24",
        "hint": "Tìm phân số của số đã cho.",
        "solution": "Số học sinh tham gia là:\n36 × (2/3) = 24 (học sinh).\nĐáp số: 24 học sinh.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q4",
        "section": "practice",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": []
      },
      {
        "prompt": "Tìm 1/2 của 12.",
        "answer": "6",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "12 × (1/2) = 12 : 2 × 1 = 6.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q5",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Tìm phân số của một số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 1/3 của 15.",
        "answer": "5",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "15 × (1/3) = 15 : 3 × 1 = 5.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q6",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Tìm phân số của một số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 1/4 của 20.",
        "answer": "5",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "20 × (1/4) = 20 : 4 × 1 = 5.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q7",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Tìm phân số của một số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/5 của 25.",
        "answer": "10",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "25 × (2/5) = 25 : 5 × 2 = 10.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q8",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "foundation",
        "skill": "Tìm phân số của một số",
        "difficulty": "easy",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/3 của 18.",
        "answer": "12",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "18 × (2/3) = 18 : 3 × 2 = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q9",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 3/4 của 28.",
        "answer": "21",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "28 × (3/4) = 28 : 4 × 3 = 21.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q10",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/7 của 35.",
        "answer": "10",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "35 × (2/7) = 35 : 7 × 2 = 10.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q11",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 5/6 của 48.",
        "answer": "40",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "48 × (5/6) = 48 : 6 × 5 = 40.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q12",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 3/8 của 40.",
        "answer": "15",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "40 × (3/8) = 40 : 8 × 3 = 15.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q13",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 4/9 của 63.",
        "answer": "28",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "63 × (4/9) = 63 : 9 × 4 = 28.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q14",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 2/5 của 30.",
        "answer": "12",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "30 × (2/5) = 30 : 5 × 2 = 12.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q15",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Tìm 3/7 của 56.",
        "answer": "24",
        "hint": "Lấy số đã cho nhân với phân số.",
        "solution": "56 × (3/7) = 56 : 7 × 3 = 24.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q16",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "skills",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Lớp có 36 học sinh, 2/3 số học sinh tham gia câu lạc bộ. Có bao nhiêu học sinh tham gia?",
        "answer": "24",
        "hint": "Tìm phân số của số đã cho.",
        "solution": "Số học sinh tham gia là:\n36 × (2/3) = 24 (học sinh).\nĐáp số: 24 học sinh.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q17",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 24 quả cam. Lấy 3/4 số đó thì được bao nhiêu quả cam?",
        "answer": "18",
        "hint": "Tìm phân số của số đã cho.",
        "solution": "Số quả cam lấy được là:\n24 × (3/4) = 18 (quả).\nĐáp số: 18 quả cam.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q18",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 45 quyển vở. Lấy 2/5 số đó thì được bao nhiêu quyển vở?",
        "answer": "18",
        "hint": "Tìm phân số của số đã cho.",
        "solution": "Số quyển vở lấy được là:\n45 × (2/5) = 18 (quyển).\nĐáp số: 18 quyển vở.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q19",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 32 chiếc bút. Lấy 3/8 số đó thì được bao nhiêu chiếc bút?",
        "answer": "12",
        "hint": "Tìm phân số của số đã cho.",
        "solution": "Số chiếc bút lấy được là:\n32 × (3/8) = 12 (chiếc).\nĐáp số: 12 chiếc bút.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q20",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 40 quyển vở, đã phát 3/5 số vở. Còn lại bao nhiêu quyển?",
        "answer": "16",
        "hint": "Tìm số đã phát, rồi lấy tổng trừ số đã phát.",
        "solution": "Số vở đã phát là:\n40 × (3/5) = 24 (quyển).\nSố vở còn lại là:\n40 − 24 = 16 (quyển).\nĐáp số: 16 quyển vở.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q21",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 60 quyển vở, đã phát 2/3 số vở. Còn lại bao nhiêu quyển?",
        "answer": "20",
        "hint": "Tìm số đã phát, rồi lấy tổng trừ số đã phát.",
        "solution": "Số vở đã phát là:\n60 × (2/3) = 40 (quyển).\nSố vở còn lại là:\n60 − 40 = 20 (quyển).\nĐáp số: 20 quyển vở.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q22",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "application",
        "skill": "Tìm phân số của một số",
        "difficulty": "medium",
        "workspace": "medium"
      },
      {
        "prompt": "Có 48 quyển vở, đã phát 3/4 số vở. Còn lại bao nhiêu quyển?",
        "answer": "12",
        "hint": "Tìm số đã phát, rồi lấy tổng trừ số đã phát.",
        "solution": "Số vở đã phát là:\n48 × (3/4) = 36 (quyển).\nSố vở còn lại là:\n48 − 36 = 12 (quyển).\nĐáp số: 12 quyển vở.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q23",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Tìm phân số của một số",
        "difficulty": "hard",
        "workspace": "medium"
      },
      {
        "prompt": "Có 72 quyển vở, đã phát 5/6 số vở. Còn lại bao nhiêu quyển?",
        "answer": "12",
        "hint": "Tìm số đã phát, rồi lấy tổng trừ số đã phát.",
        "solution": "Số vở đã phát là:\n72 × (5/6) = 60 (quyển).\nSố vở còn lại là:\n72 − 60 = 12 (quyển).\nĐáp số: 12 quyển vở.",
        "options": [],
        "kind": "number",
        "id": "math-fraction-of-number-4-q24",
        "section": "extra",
        "unit": "",
        "simplified": false,
        "tolerance": 0,
        "mistakes": [],
        "group": "challenge",
        "skill": "Tìm phân số của một số",
        "difficulty": "hard",
        "workspace": "medium"
      }
    ]
  }
];
