import type { MathExercise, MathLessonData } from './lessons';
import { rationalExponentEquations } from './rational-exponent-equations';

export const rationalExponentReview: MathExercise[] = [
  {
    id: 're-review-1',
    section: 'extra',
    task: 'Tính — ôn nền tảng',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính 2^0.',
    answer: '1',
    hint: 'Với cơ số khác 0, lũy thừa có số mũ 0 bằng 1.',
    solution: '2^0 = 1.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-2',
    section: 'extra',
    task: 'Tính — ôn nền tảng',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính 2^1.',
    answer: '2',
    hint: 'Lũy thừa có số mũ 1 bằng chính cơ số.',
    solution: '2^1 = 2.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-3',
    section: 'extra',
    task: 'Tính — ôn nền tảng',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính 2^4.',
    answer: '16',
    hint: 'Viết thành tích của bốn thừa số 2.',
    solution: '2^4 = 2 × 2 × 2 × 2 = 16.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-4',
    section: 'extra',
    task: 'Tính — ôn nền tảng',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính (-2)^2.',
    answer: '4',
    hint: 'Số mũ chẵn: tích hai số âm là số dương.',
    solution: '(-2)^2 = (-2) × (-2) = 4.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-5',
    section: 'extra',
    task: 'Tính — ôn nền tảng',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính (-2)^3.',
    answer: '-8',
    hint: 'Số mũ lẻ: kết quả mang dấu âm.',
    solution: '(-2)^3 = (-2) × (-2) × (-2) = -8.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-6',
    section: 'extra',
    task: 'Tính — ôn các quy tắc lũy thừa',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính 2^2 × 2^3.',
    answer: '32',
    hint: 'Nhân hai lũy thừa cùng cơ số: cộng các số mũ.',
    solution: '2^2 × 2^3 = 2^(2 + 3) = 2^5 = 32.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-7',
    section: 'extra',
    task: 'Tính — ôn các quy tắc lũy thừa',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính (2^3)^2.',
    answer: '64',
    hint: 'Lũy thừa của lũy thừa: nhân các số mũ.',
    solution: '(2^3)^2 = 2^(3 × 2) = 2^6 = 64.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-8',
    section: 'extra',
    task: 'Tính — ôn các quy tắc lũy thừa',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính (2^2)^3.',
    answer: '64',
    hint: 'Nhân số mũ 2 với 3.',
    solution: '(2^2)^3 = 2^(2 × 3) = 2^6 = 64.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-9',
    section: 'extra',
    task: 'Tính — ôn các quy tắc lũy thừa',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'number',
    prompt: 'Tính 2^3 : 2^2.',
    answer: '2',
    hint: 'Chia hai lũy thừa cùng cơ số khác 0: trừ các số mũ.',
    solution: '2^3 : 2^2 = 2^(3 - 2) = 2^1 = 2.',
    unit: '',
    options: [],
    simplified: false,
    tolerance: 0,
    mistakes: [],
  },
  {
    id: 're-review-10',
    section: 'extra',
    task: 'Tính — ôn các quy tắc lũy thừa',
    group: 'foundation',
    skill: 'Ôn nền tảng về lũy thừa',
    difficulty: 'easy',
    workspace: 'small',
    kind: 'fraction',
    prompt: 'Tính (1/2)^2.',
    answer: '1/4',
    hint: 'Bình phương cả tử và mẫu.',
    solution: '(1/2)^2 = 1/2 × 1/2 = 1/4.',
    unit: '',
    options: [],
    simplified: true,
    tolerance: 0,
    mistakes: [],
  },
];

export const rationalExponentsLesson: MathLessonData = {
  id: 'math-rational-exponents-7',
  title: 'Lũy thừa với số mũ tự nhiên của một số hữu tỉ',
  grade: 7,
  semester: '1',
  topic: 'Số hữu tỉ',
  goal: 'Nhận biết và tính lũy thừa của số hữu tỉ; vận dụng quy tắc nhân, chia hai lũy thừa cùng cơ số và lũy thừa của một lũy thừa.',
  textbook:
    'Nội dung tham khảo yêu cầu cần đạt mạch Số và Đại số, Toán 7 Chương trình Giáo dục phổ thông 2018. Giáo viên cần đối chiếu sách giáo khoa đang sử dụng trước khi dạy chính thức.',
  teacherNotes:
    'Bắt đầu bằng tích các thừa số bằng nhau. Với mỗi quy tắc mới, cho học sinh khai triển một ví dụ rồi mới nêu quy tắc. Khi chia, chỉ dùng cơ số khác 0 và số mũ của số bị chia không nhỏ hơn số mũ của số chia.',
  knowledgeSummary:
    '- Với số hữu tỉ x và số tự nhiên n khác 0: x^n = x × x × ... × x (n thừa số x). x là cơ số, n là số mũ.\n- Với x khác 0, x^0 = 1. Riêng 0^0 không xác định.\n- Cơ số âm: số mũ chẵn cho kết quả dương, số mũ lẻ cho kết quả âm.\n- Nhân cùng cơ số: a^m × a^n = a^(m + n). Chia cùng cơ số khác 0, với m ≥ n: a^m : a^n = a^(m - n).\n- Lũy thừa của lũy thừa: (a^m)^n = a^(m × n).\n- Ví dụ: (2^2)^3 = 2^(2 × 3) = 2^6 = 64.\n- Ví dụ với phân số: (1/2)^2 × (1/2)^3 = (1/2)^5 = 1/32; [(-1/2)^2]^3 = (-1/2)^6 = 1/64.\n- Lưu ý: Khi nhân thì cộng số mũ, khi chia thì trừ số mũ, còn lũy thừa của lũy thừa thì nhân số mũ.',
  blocks: [
    {
      id: 're-foundation',
      section: 'foundation',
      title: 'Khởi động',
      text: 'Hãy viết gọn tích 2 × 2 × 2. Ta viết 2^3 và đọc là “hai mũ ba”. Số 2 gọi là cơ số, số 3 gọi là số mũ. Số mũ cho biết cơ số được lấy làm thừa số bao nhiêu lần.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-definition',
      section: 'explore',
      title: 'HĐ 1. Lũy thừa của một số hữu tỉ',
      text: 'Xét tích 2/3 × 2/3 × 2/3. Ba thừa số đều bằng 2/3 nên ta viết gọn là (2/3)^3. Như vậy, (2/3)^3 = 2/3 × 2/3 × 2/3. Số 2/3 là cơ số; số 3 cho biết có ba thừa số 2/3.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-sign',
      section: 'explore',
      title: 'HĐ 2. Dấu của lũy thừa',
      text: 'Bây giờ xét cơ số âm. Ta có (-1/2)^2 = (-1/2) × (-1/2) = 1/4. Còn (-1/2)^3 = (-1/2) × (-1/2) × (-1/2) = -1/8. Nhận xét: cơ số âm có số mũ chẵn cho lũy thừa dương; cơ số âm có số mũ lẻ cho lũy thừa âm.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-zero',
      section: 'explore',
      title: 'Ghi nhớ',
      text: 'Với số hữu tỉ x và số tự nhiên n khác 0:\nx^n = x × x × ... × x (n thừa số x).\n\nKhi cơ số âm, phải đặt cơ số trong ngoặc.\nVới x khác 0: x^0 = 1.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-same-base-discover',
      section: 'explore',
      title: 'Nhân và chia 2 lũy thừa cùng cơ số',
      text: 'Xét phép nhân:\n2^2 × 2^3 = (2 × 2) × (2 × 2 × 2) = 2^5.\nCó 2 + 3 = 5 thừa số 2.\n\nXét phép chia:\n2^5 : 2^2\n= (2 × 2 × 2 × ~2~ × ~2~)/(~2~ × ~2~)\n= 2 × 2 × 2\n= 2^3.\n\nTa rút gọn hai thừa số 2 ở tử và mẫu, còn 3 thừa số 2.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-same-base-rule',
      section: 'explore',
      title: 'Ghi nhớ: cùng cơ số',
      text: 'Khi nhân hai lũy thừa cùng cơ số:\nGiữ nguyên cơ số, cộng các số mũ.\na^m × a^n = a^(m + n).\n\nKhi chia hai lũy thừa cùng cơ số khác 0:\nGiữ nguyên cơ số, trừ các số mũ.\na^m : a^n = a^(m - n), với m ≥ n.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-power-discover',
      section: 'explore',
      title: 'Lũy thừa của lũy thừa',
      text: 'Xét (2^3)^2.\nSố mũ 2 cho biết lấy 2^3 hai lần.\n\n(2^3)^2 = 2^3 × 2^3 = 2^6.\nCó 2 nhóm, mỗi nhóm có 3 thừa số 2.\nVậy có 3 × 2 = 6 thừa số 2.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-power-rule',
      section: 'explore',
      title: 'Ghi nhớ: lũy thừa của lũy thừa',
      text: 'Khi tính lũy thừa của một lũy thừa:\nGiữ nguyên cơ số, nhân các số mũ.\n\n(a^m)^n = a^(m × n).\n\nKhông cộng các số mũ trong trường hợp này.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-example-1',
      section: 'example',
      title: 'Ví dụ 1',
      text: 'Tính (2/3)^2. Theo ý nghĩa của lũy thừa: (2/3)^2 = 2/3 × 2/3 = 4/9. Vậy (2/3)^2 = 4/9.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-example-2',
      section: 'example',
      title: 'Ví dụ 2',
      text: 'Tính (-1/2)^3. Ta viết: (-1/2)^3 = (-1/2) × (-1/2) × (-1/2) = -1/8. Có ba thừa số âm nên kết quả là số âm.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-example-3',
      section: 'example',
      title: 'Ví dụ 3',
      text: 'Tính (1/2)^1 × (1/2)^2.\nHai lũy thừa có cùng cơ số 1/2.\n\n(1/2)^1 × (1/2)^2\n= (1/2)^(1 + 2)\n= (1/2)^3\n= 1/8.',
      visual: 'none',
      values: [],
    },
    {
      id: 're-example-4',
      section: 'example',
      title: 'Ví dụ 4',
      text: 'Tính [(-1/2)^2]^2.\nĐây là lũy thừa của một lũy thừa.\n\n[(-1/2)^2]^2\n= (-1/2)^(2 × 2)\n= (-1/2)^4\n= 1/16.',
      visual: 'none',
      values: [],
    },
  ],
  exercises: [
    ...rationalExponentReview,
    {
      id: 're-ex-1',
      section: 'foundation',
      kind: 'choice',
      prompt: 'Khởi động. (2/3)^3 là cách viết gọn của tích nào?',
      answer: '2/3 × 2/3 × 2/3',
      hint: 'Số mũ 3 cho biết có ba thừa số bằng 2/3.',
      solution: '(2/3)^3 = 2/3 × 2/3 × 2/3.',
      unit: '',
      options: ['2/3 × 2/3 × 2/3', '2/3 × 3', '2/3 + 2/3 + 2/3'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-2',
      section: 'guided',
      kind: 'fraction',
      prompt: 'Luyện tập 1. Tính (1/2)^4 : (1/2)^2.',
      answer: '1/4',
      hint: 'Giữ cơ số 1/2 và lấy 4 - 2.',
      solution: '(1/2)^4 : (1/2)^2\n= (1/2)^2\n= 1/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-3',
      section: 'practice',
      kind: 'fraction',
      prompt: 'Luyện tập 2. Tính (1/2)^3.',
      answer: '1/8',
      hint: 'Viết thành tích của ba thừa số 1/2.',
      solution: '(1/2)^3\n= 1/2 × 1/2 × 1/2\n= 1/8.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-4',
      section: 'practice',
      kind: 'fraction',
      prompt: 'Luyện tập 3. Tính (-1/2)^3.',
      answer: '-1/8',
      hint: 'Số mũ lẻ nên kết quả mang dấu âm.',
      solution: '(-1/2)^3 = -1/8.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-5',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 4. Tính (2/3)^0.',
      answer: '1',
      hint: 'Cơ số 2/3 khác 0.',
      solution: '(2/3)^0 = 1.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-6',
      section: 'practice',
      kind: 'choice',
      prompt: 'Luyện tập 5. Giá trị của (-1/2)^2 là bao nhiêu?',
      answer: '1/4',
      hint: 'Có hai thừa số âm nên tích dương.',
      solution: '(-1/2)^2 = 1/4.',
      unit: '',
      options: ['1/4', '-1/4', '-1/8'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-7',
      section: 'extra',
      task: 'Tính giá trị biểu thức',
      kind: 'number',
      prompt: 'Tính 1 - (-2)^3.',
      answer: '9',
      hint: 'Tính lũy thừa trước.',
      solution: '1 - (-2)^3\n= 1 - (-8)\n= 9.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-8',
      section: 'extra',
      task: 'Tính giá trị biểu thức',
      kind: 'fraction',
      prompt: 'Tính (-1/3)^2 × (-1/3).',
      answer: '-1/27',
      hint: 'Tính lũy thừa rồi nhân với -1/3.',
      solution: '(-1/3)^2 × (-1/3)\n= 1/9 × (-1/3)\n= -1/27.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-9',
      section: 'practice',
      kind: 'choice',
      prompt: 'Luyện tập 6. 5^2 × 5^4 bằng lũy thừa nào?',
      answer: '5^6',
      hint: 'Khi nhân cùng cơ số, cộng số mũ.',
      solution: '5^2 × 5^4\n= 5^(2 + 4)\n= 5^6.',
      unit: '',
      options: ['5^6', '5^8', '10^6'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-10',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 7. Tính 2^3 × 2^4.',
      answer: '128',
      hint: '2^3 × 2^4 = 2^(3 + 4).',
      solution: '2^3 × 2^4\n= 2^7\n= 128.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-11',
      section: 'practice',
      kind: 'fraction',
      prompt: 'Luyện tập 8. Tính (-1/2)^2 × (-1/2)^3.',
      answer: '-1/32',
      hint: 'Cộng số mũ: 2 + 3 = 5.',
      solution: '(-1/2)^2 × (-1/2)^3\n= (-1/2)^5\n= -1/32.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-12',
      section: 'practice',
      kind: 'choice',
      prompt: 'Luyện tập 9. 7^6 : 7^2 bằng lũy thừa nào?',
      answer: '7^4',
      hint: 'Khi chia cùng cơ số, trừ số mũ.',
      solution: '7^6 : 7^2\n= 7^(6 - 2)\n= 7^4.',
      unit: '',
      options: ['7^3', '7^4', '7^8'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-13',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 10. Tính 3^5 : 3^3.',
      answer: '9',
      hint: '3^5 : 3^3 = 3^(5 - 3).',
      solution: '3^5 : 3^3\n= 3^2\n= 9.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-14',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 11. Tính (-2)^5 : (-2)^3.',
      answer: '4',
      hint: 'Giữ cơ số -2 và lấy 5 - 3.',
      solution: '(-2)^5 : (-2)^3\n= (-2)^2\n= 4.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-15',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 12. Tính (5/6)^4 : (5/6)^4.',
      answer: '1',
      hint: 'Số mũ của kết quả là 4 - 4 = 0.',
      solution: '(5/6)^4 : (5/6)^4\n= (5/6)^0\n= 1.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-16',
      section: 'practice',
      kind: 'choice',
      prompt: 'Luyện tập 13. (3^2)^4 bằng lũy thừa nào?',
      answer: '3^8',
      hint: 'Lũy thừa của lũy thừa: nhân các số mũ.',
      solution: '(3^2)^4\n= 3^(2 × 4)\n= 3^8.',
      unit: '',
      options: ['3^6', '3^8', '3^16'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-17',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 14. Tính (2^2)^3.',
      answer: '64',
      hint: 'Nhân các số mũ: 2 × 3 = 6.',
      solution: '(2^2)^3\n= 2^6\n= 64.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-18',
      section: 'practice',
      kind: 'number',
      prompt: 'Luyện tập 15. Tính ((-2)^2)^3.',
      answer: '64',
      hint: 'Đây là lũy thừa của lũy thừa; số mũ cuối cùng là 2 × 3.',
      solution: '((-2)^2)^3\n= (-2)^6\n= 64.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-19',
      section: 'extra',
      task: 'Tính — phối hợp các quy tắc',
      kind: 'fraction',
      prompt: 'Tính [(-1/2)^3]^2.',
      answer: '1/64',
      hint: 'Nhân các số mũ: 3 × 2 = 6.',
      solution: '[(-1/2)^3]^2\n= (-1/2)^6\n= 1/64.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-20',
      section: 'extra',
      task: 'Tính — phối hợp các quy tắc',
      kind: 'number',
      prompt: 'Tính 2^3 × 2^5 : 2^4.',
      answer: '16',
      hint: 'Có thể cộng 3 và 5 trước, rồi trừ 4.',
      solution: '2^3 × 2^5 : 2^4\n= 2^(3 + 5 - 4)\n= 2^4\n= 16.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-21',
      section: 'extra',
      task: 'Tính — phối hợp các quy tắc',
      kind: 'fraction',
      prompt: 'Tính (2/3)^2 × (2/3)^3 : (2/3)^4.',
      answer: '2/3',
      hint: 'Số mũ kết quả là 2 + 3 - 4.',
      solution:
        '(2/3)^2 × (2/3)^3 : (2/3)^4\n= (2/3)^(2 + 3 - 4)\n= (2/3)^1\n= 2/3.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-22',
      section: 'extra',
      task: 'Tính — phối hợp các quy tắc',
      kind: 'number',
      prompt: 'Tính (2^2)^3 : 2^4.',
      answer: '4',
      hint: 'Tính lũy thừa của lũy thừa trước.',
      solution:
        '(2^2)^3 : 2^4\n= 2^(2 × 3) : 2^4\n= 2^6 : 2^4\n= 2^(6 - 4)\n= 2^2\n= 4.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-23',
      section: 'extra',
      task: 'Tính — phối hợp các quy tắc',
      kind: 'choice',
      prompt:
        'Điều kiện nào cần có để áp dụng a^m : a^n = a^(m - n) trong bài học này?',
      answer: 'a khác 0 và m không nhỏ hơn n',
      hint: 'Không được chia cho 0; bài này chỉ dùng số mũ tự nhiên.',
      solution:
        'Cần a khác 0 để phép chia có nghĩa và m không nhỏ hơn n để m - n là số tự nhiên.',
      unit: '',
      options: [
        'a khác 0 và m không nhỏ hơn n',
        'a phải dương',
        'm phải lớn hơn n',
      ],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-24',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'number',
      prompt: 'Tính 3^2 × 3^3 : 3^4.',
      answer: '3',
      hint: 'Gộp các số mũ: 2 + 3 - 4.',
      solution: '3^2 × 3^3 : 3^4\n= 3^(2 + 3 - 4)\n= 3.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-25',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'number',
      prompt: 'Tính (-2)^4 : (-2)^2.',
      answer: '4',
      hint: 'Giữ cơ số -2 và lấy 4 - 2.',
      solution: '(-2)^4 : (-2)^2\n= (-2)^(4 - 2)\n= (-2)^2\n= 4.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-26',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'fraction',
      prompt: 'Tính (1/2)^2 × (1/2)^3 : (1/2)^4.',
      answer: '1/2',
      hint: 'Số mũ kết quả là 2 + 3 - 4.',
      solution:
        '(1/2)^2 × (1/2)^3 : (1/2)^4\n= (1/2)^(2 + 3 - 4)\n= (1/2)^1\n= 1/2.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-27',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'fraction',
      prompt: 'Tính 4 × (1/2)^3.',
      answer: '1/2',
      hint: '(1/2)^3 = 1/8; sau đó nhân với 4.',
      solution: '4 × (1/2)^3\n= 4 × 1/8\n= 1/2.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-28',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'number',
      prompt: 'Tính (3/2)^2 × (2/3)^2.',
      answer: '1',
      hint: 'Tính từng lũy thừa rồi rút gọn tích.',
      solution: '(3/2)^2 × (2/3)^2\n= 9/4 × 4/9\n= 1.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-29',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'fraction',
      prompt: 'Tính [(-1/2)^2]^3.',
      answer: '1/64',
      hint: 'Nhân số mũ 2 với số mũ 3.',
      solution: '[(-1/2)^2]^3\n= (-1/2)^6\n= 1/64.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-30',
      section: 'extra',
      task: 'Tính — luyện tập với số hữu tỉ',
      kind: 'number',
      prompt: 'Tính 1 - (-2)^4.',
      answer: '-15',
      hint: 'Tính lũy thừa trước: (-2)^4 là số dương.',
      solution: '1 - (-2)^4\n= 1 - 16\n= -15.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-31',
      section: 'extra',
      kind: 'choice',
      prompt: 'Biểu thức nào bằng 7^5?',
      answer: '7^2 × 7^3',
      hint: 'Khi nhân hai lũy thừa cùng cơ số, cộng số mũ.',
      solution: '7^2 × 7^3\n= 7^(2 + 3)\n= 7^5.',
      unit: '',
      options: ['7^2 × 7^3', '7^8 : 7^2', '(7^2)^3'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-32',
      section: 'extra',
      task: 'Tính dựa vào lũy thừa đã biết',
      kind: 'number',
      prompt: 'Biết (-2)^5 = -32. Tính (-2)^6.',
      answer: '64',
      hint: 'Nhân (-2)^5 với thêm một thừa số -2.',
      solution: '(-2)^6\n= (-2)^5 × (-2)\n= (-32) × (-2)\n= 64.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-33',
      section: 'extra',
      task: 'Tính dựa vào lũy thừa đã biết',
      kind: 'fraction',
      prompt: 'Biết (-1/2)^4 = 1/16. Tính (-1/2)^5.',
      answer: '-1/32',
      hint: 'Nhân giá trị đã biết với thêm một thừa số -1/2.',
      solution: '(-1/2)^5\n= 1/16 × (-1/2)\n= -1/32.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-34',
      section: 'extra',
      kind: 'choice',
      prompt: 'Viết 2^6 × 4^3 dưới dạng một lũy thừa của cơ số 2.',
      answer: '2^12',
      hint: 'Đổi 4^3 thành (2^2)^3 trước.',
      solution: '2^6 × 4^3\n= 2^6 × (2^2)^3\n= 2^6 × 2^6\n= 2^12.',
      unit: '',
      options: ['2^9', '2^12', '8^9'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-35',
      section: 'extra',
      task: 'Tính biểu thức',
      kind: 'number',
      prompt: 'Tính (1 + 1/2)^2 × 4/9.',
      answer: '1',
      hint: 'Tính 1 + 1/2 trước.',
      solution:
        '(1 + 1/2)^2 × 4/9\n= (3/2)^2 × 4/9\n= 9/4 × 4/9\n= (9 × 4)/(4 × 9)\n= 1.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-36',
      section: 'extra',
      task: 'Tính biểu thức',
      kind: 'fraction',
      prompt: 'Tính 4 × (1/2 - 1/4)^2.',
      answer: '1/4',
      hint: 'Tính hiệu trong ngoặc trước.',
      solution: '4 × (1/2 - 1/4)^2\n= 4 × (1/4)^2\n= 4 × 1/(4 × 4)\n= 1/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-37',
      section: 'extra',
      task: 'Tính biểu thức',
      kind: 'number',
      prompt: 'Tính (1/2)^2 : (1/4)^2.',
      answer: '4',
      hint: 'Tính hai lũy thừa rồi thực hiện phép chia.',
      solution:
        '(1/2)^2 : (1/4)^2\n= 1/4 : 1/(4 × 4)\n= 1/~4~ × (~4~ × 4)/1\n= 4.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-38',
      section: 'extra',
      task: 'Tính một cách hợp lí',
      kind: 'number',
      prompt: 'Tính một cách hợp lí: 4,75 + (-1/2)^3 + 0,5^2 - 3 × (-3/8).',
      answer: '6',
      hint: 'Đổi 4,75 thành 19/4 và 0,5^2 thành 1/4.',
      solution:
        '4,75 + (-1/2)^3 + 0,5^2 - 3 × (-3/8)\n= 4,75 - 1/8 + 1/4 - 3 × (-3/8)\n= 19/4 - 1/8 + 1/4 + 9/8\n= 20/4 + 8/8\n= 20/4 + 4/4\n= 24/4\n= 6.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-39',
      section: 'extra',
      task: 'Tính một cách hợp lí',
      kind: 'fraction',
      prompt: 'Tính một cách hợp lí: 5/4 + (-1/2)^3 - (1/2)^2.',
      answer: '7/8',
      hint: 'Tính hai lũy thừa rồi quy đồng mẫu số 8.',
      solution:
        '5/4 + (-1/2)^3 - (1/2)^2\n= 5/4 - 1/8 - 1/4\n= 10/8 - 1/8 - 2/8\n= (10 - 1 - 2)/8\n= 7/8.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-40',
      section: 'extra',
      task: 'Tính một cách hợp lí',
      kind: 'fraction',
      prompt: 'Tính một cách hợp lí: (3/2)^2 - 2 × (1/2)^2.',
      answer: '7/4',
      hint: 'Tính từng lũy thừa trước.',
      solution:
        '(3/2)^2 - 2 × (1/2)^2\n= 9/4 - 2 × 1/4\n= 9/4 - 2/4\n= (9 - 2)/4\n= 7/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-41',
      section: 'extra',
      task: 'Tính một cách hợp lí',
      kind: 'fraction',
      prompt: 'Tính một cách hợp lí: 1 - (-1/2)^2 - 3 × (-1/2)^3.',
      answer: '9/8',
      hint: 'Chú ý: (-1/2)^3 là số âm.',
      solution:
        '1 - (-1/2)^2 - 3 × (-1/2)^3\n= 1 - 1/4 - 3 × (-1/8)\n= 1 - 1/4 + 3/8\n= 8/8 - 2/8 + 3/8\n= 9/8.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-42',
      section: 'extra',
      task: 'Tính một cách hợp lí',
      kind: 'fraction',
      prompt: 'Tính một cách hợp lí: 2,5 - 4 × (1/2)^2 + (-1/2)^3.',
      answer: '11/8',
      hint: 'Viết 2,5 dưới dạng phân số rồi tính các lũy thừa.',
      solution:
        '2,5 - 4 × (1/2)^2 + (-1/2)^3\n= 5/2 - 4 × 1/4 - 1/8\n= 5/2 - 1 - 1/8\n= 20/8 - 8/8 - 1/8\n= 11/8.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-43',
      section: 'extra',
      task: 'Giải bài toán thực tế',
      kind: 'number',
      prompt:
        'Ước tính khoảng cách từ Sao Hỏa đến Mặt Trời là 2,4 × 10^8 km, còn khoảng cách từ Trái Đất đến Mặt Trời là 1,5 × 10^8 km. Hỏi khoảng cách từ Sao Hỏa đến Mặt Trời gấp bao nhiêu lần khoảng cách từ Trái Đất đến Mặt Trời?',
      answer: '1,6',
      hint: 'Lập tỉ số 2,4 × 10^8 : (1,5 × 10^8), rồi rút gọn 10^8.',
      solution:
        'Khoảng cách từ Sao Hỏa đến Mặt Trời gấp số lần khoảng cách từ Trái Đất đến Mặt Trời là:\n(2,4 × 10^8) : (1,5 × 10^8)= 1,6 (lần).\nĐáp số: 1,6 lần.',
      unit: 'lần',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-44',
      section: 'extra',
      task: 'Giải bài toán thực tế',
      kind: 'number',
      prompt:
        'Ước tính khoảng cách từ Sao Thổ đến Mặt Trời là 1,5 × 10^9 km, còn khoảng cách từ Sao Mộc đến Mặt Trời là 7,5 × 10^8 km. Hỏi khoảng cách từ Sao Thổ đến Mặt Trời gấp bao nhiêu lần khoảng cách từ Sao Mộc đến Mặt Trời?',
      answer: '2',
      hint: 'Đưa 7,5 × 10^8 về dạng 0,75 × 10^9 rồi lập tỉ số.',
      solution:
        'Khoảng cách từ Sao Thổ đến Mặt Trời gấp số lần khoảng cách từ Sao Mộc đến Mặt Trời là:\n(1,5 × 10^9) : (7,5 × 10^8)= 2 (lần).\nĐáp số: 2 lần.',
      unit: 'lần',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 're-ex-45',
      section: 'extra',
      task: 'Giải bài toán thực tế',
      kind: 'number',
      prompt:
        'Ước tính khoảng cách từ Sao Hải Vương đến Mặt Trời là 4,5 × 10^9 km, còn khoảng cách từ Sao Thiên Vương đến Mặt Trời là 3 × 10^9 km. Hỏi khoảng cách từ Sao Hải Vương đến Mặt Trời gấp bao nhiêu lần khoảng cách từ Sao Thiên Vương đến Mặt Trời?',
      answer: '1,5',
      hint: 'Hai số đều có thừa số 10^9 nên chỉ cần chia 4,5 cho 3.',
      solution:
        'Khoảng cách từ Sao Hải Vương đến Mặt Trời gấp số lần khoảng cách từ Sao Thiên Vương đến Mặt Trời là:\n(4,5 × 10^9) : (3 × 10^9)= 1,5 (lần).\nĐáp số: 1,5 lần.',
      unit: 'lần',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    ...rationalExponentEquations,
  ],
};

export function addRationalExponentReview(
  lessons: MathLessonData[]
): MathLessonData[] {
  return lessons.map((lesson) => {
    if (lesson.id !== rationalExponentsLesson.id) return lesson;
    const ids = new Set(rationalExponentReview.map((e) => e.id));
    const missing = rationalExponentReview.filter(
      (e) => !lesson.exercises.some((old) => old.id === e.id)
    );
    if (lesson.exercises.length + missing.length > 100) return lesson;
    const review = rationalExponentReview.map(
      (e) =>
        lesson.exercises.find((old) => old.id === e.id) ?? structuredClone(e)
    );
    return {
      ...lesson,
      exercises: [...review, ...lesson.exercises.filter((e) => !ids.has(e.id))],
    };
  });
}

export function groupRationalExponentExercises(
  lessons: MathLessonData[]
): MathLessonData[] {
  return lessons.map((lesson) =>
    lesson.id !== rationalExponentsLesson.id
      ? lesson
      : {
          ...lesson,
          exercises: lesson.exercises.map((e) => {
            const source = rationalExponentsLesson.exercises.find(
              (item) => item.id === e.id
            );
            return e.task === undefined &&
              source?.task &&
              source.prompt === e.prompt
              ? { ...e, task: source.task }
              : e;
          }),
        }
  );
}

export function addExponentSummaryExample(
  lessons: MathLessonData[]
): MathLessonData[] {
  const summary = rationalExponentsLesson.knowledgeSummary!;
  const previousSummary = summary.replace(
    '(1/2)^2 × (1/2)^3 = (1/2)^5 = 1/32;',
    '(2/3)^2 × (2/3)^3 = (2/3)^5 = 32/243;'
  );
  const withoutFractionResults = previousSummary
    .replace('(2/3)^5 = 32/243;', '(2/3)^5;')
    .replace('(-1/2)^6 = 1/64.', '(-1/2)^6.');
  const previous = new Set([
    previousSummary,
    withoutFractionResults,
    withoutFractionResults.replace('2^6 = 64.', '2^6.'),
    withoutFractionResults
      .replace('- Ví dụ: (2^2)^3 = 2^(2 × 3) = 2^6 = 64.\n', '')
      .replace('- Ví dụ với phân số:', '- Ví dụ:'),
  ]);
  return lessons.map((lesson) =>
    lesson.id === rationalExponentsLesson.id &&
    previous.has(lesson.knowledgeSummary ?? '')
      ? { ...lesson, knowledgeSummary: summary }
      : lesson
  );
}
