import { rationalSetBlocks, rationalSetExercises } from './set-content';
import { MathLessonData } from './lessons';
import { builtInExercisePrompts } from './exercise-content';

export const rationalLesson: MathLessonData = {
  id: 'math-rational-7',
  title: 'Số hữu tỉ: nhận biết, so sánh và tính toán',
  grade: 7,
  topic: 'Số hữu tỉ',
  goal: 'Nhận biết số hữu tỉ, biểu diễn trên trục số, so sánh và thực hiện bốn phép tính với số hữu tỉ.',
  textbook:
    'Bài tự biên soạn theo chủ đề Số hữu tỉ lớp 7; chưa gắn với trang hoặc ấn bản sách cụ thể.',
  teacherNotes:
    'Có thể chia thành hai buổi: nhận biết và so sánh; bốn phép tính và vận dụng. Nhấn mạnh mẫu khác 0, mẫu dương khi so sánh và dấu khi tính. Bài chưa bao gồm lũy thừa.',
  blocks: [
    ...rationalSetBlocks,
    {
      id: 'r-block-1',
      section: 'foundation',
      title: 'Ôn lại phân số và số nguyên',
      text: 'Phân số có mẫu khác 0. Nhân hoặc chia cả tử và mẫu với cùng một số nguyên khác 0 tạo phân số bằng nó.\n\nMuốn cộng hai số nguyên khác dấu (không đối nhau), ta tìm hiệu của hai phần số tự nhiên của chúng (số lớn trừ số nhỏ) rồi đặt trước hiệu tìm được dấu của số có phần số tự nhiên lớn hơn.\nVí dụ: (-8) + 5 = -(8 − 5) = -3.\nHai số nguyên đối nhau có tổng bằng 0. Ví dụ: (-5) + 5 = 0.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-2',
      section: 'explore',
      title: 'Số hữu tỉ là gì?',
      text: 'Số hữu tỉ là số viết được dưới dạng a/b, với a, b là số nguyên và b khác 0. Tập hợp số hữu tỉ kí hiệu là ℚ. Ví dụ: -3 = -3/1; 0 = 0/1; 0,75 = 75/100 = 3/4. Mỗi số nguyên đều là số hữu tỉ. Một số hữu tỉ có thể được biểu diễn bằng nhiều phân số bằng nhau.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-3',
      section: 'explore',
      title: 'Dấu, số đối và trục số',
      text: 'Ta thường viết phân số với mẫu dương. Ví dụ: 2/(-3) = -2/3 và (-2)/(-3) = 2/3. Số hữu tỉ dương nằm bên phải 0, số hữu tỉ âm nằm bên trái 0; số 0 không dương cũng không âm. Chia đoạn từ 0 đến 1 thành 4 phần bằng nhau: điểm 3/4 cách 0 ba phần về bên phải. Số đối của 3/4 là -3/4; hai số đối có tổng bằng 0.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-4',
      section: 'explore',
      title: 'So sánh hai số hữu tỉ',
      text: 'Trên trục số, số nằm bên trái nhỏ hơn số nằm bên phải. Để so sánh hai phân số, đưa về cùng mẫu dương rồi so sánh tử số. Ví dụ: -2/3 = -8/12 và -3/4 = -9/12. Vì -8 > -9 nên -2/3 > -3/4.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-5',
      section: 'explore',
      title: 'Bốn phép tính',
      text: 'Cộng, trừ: quy đồng mẫu dương rồi cộng hoặc trừ các tử số, giữ mẫu chung. Nhân: rút gọn các thừa số chung ở tử và mẫu (nếu có), rồi nhân tử với tử, mẫu với mẫu. Chia cho số khác 0: nhân với số nghịch đảo của số chia. Hai thừa số cùng dấu cho tích dương, khác dấu cho tích âm. Luôn rút gọn kết quả.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-6',
      section: 'example',
      title: '1. Quy đồng trước khi cộng',
      text: 'Tính -2/3 + 5/6. Chọn mẫu chung là 6. Ta có -2/3 = -4/6.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-7',
      section: 'example',
      title: '2. Cộng tử và rút gọn',
      text: '-4/6 + 5/6 = (-4 + 5)/6 = 1/6.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-8',
      section: 'example',
      title: '3. Trừ bằng cách cộng số đối',
      text: '-1/2 − 1/3 = -3/6 − 2/6 = -5/6. Chú ý: trừ một số âm là cộng số đối của nó, chẳng hạn 1/2 − (-1/3) = 1/2 + 1/3 = 5/6.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-9',
      section: 'example',
      title: '4. Chia bằng cách nhân với số nghịch đảo',
      text: 'Số nghịch đảo của 9/8 là 8/9. Vì vậy:\n(-3/4) : (9/8) = (-3/4) × (8/9) = (-~3~ × ~4~ × 2)/(~4~ × ~3~ × 3) = -2/3.',
      visual: 'none',
      values: [],
    },
    {
      id: 'r-block-10',
      section: 'guided',
      title: 'Tự hoàn thành từng bước',
      text: 'Tính -1/2 + 3/4: đổi -1/2 thành -2/4, rồi cộng tử số. Khi so sánh các số âm, hãy nhớ số nằm gần 0 hơn thì lớn hơn.',
      visual: 'none',
      values: [],
    },
  ],
  exercises: [
    {
      id: 'r-ex-1',
      section: 'foundation',
      kind: 'choice',
      prompt: 'Phân số nào bằng -1/2?',
      answer: '-2/4',
      hint: 'Nhân cả tử và mẫu với 2.',
      solution: '-1/2 = -2/4.',
      unit: '',
      options: ['-2/4', '2/4', '-1/4'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-2',
      section: 'foundation',
      kind: 'number',
      prompt: 'Tính -3 + 5.',
      answer: '2',
      hint: 'Hai số khác dấu: lấy 5 trừ 3.',
      solution: '-3 + 5 = 2.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-3',
      section: 'guided',
      kind: 'fraction',
      prompt: 'Tính -1/2 + 3/4. Viết phân số tối giản.',
      answer: '1/4',
      hint: 'Đổi -1/2 thành -2/4.',
      solution: '-1/2 + 3/4 = -2/4 + 3/4 = 1/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-4',
      section: 'practice',
      kind: 'choice',
      prompt: 'So sánh -2/3 và -3/4.',
      answer: '-2/3 > -3/4',
      hint: 'Quy đồng mẫu 12.',
      solution: '-2/3 = -8/12 > -9/12 = -3/4.',
      unit: '',
      options: ['-2/3 > -3/4', '-2/3 < -3/4', '-2/3 = -3/4'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-5',
      section: 'practice',
      kind: 'fraction',
      prompt: 'Tính (-3/5) × (10/9).',
      answer: '-2/3',
      hint: 'Tích hai số khác dấu là số âm.',
      solution: '(-3/5) × (10/9) = (-~3~ × ~5~ × 2)/(~5~ × ~3~ × 3) = -2/3.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-6',
      section: 'practice',
      kind: 'fraction',
      prompt: 'Tính (2/3) : (-4/5).',
      answer: '-5/6',
      hint: 'Nhân với -5/4.',
      solution:
        '(2/3) : (-4/5) = (2/3) × (-5/4) = (-~2~ × 5)/(3 × ~2~ × 2) = -5/6.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
    },
    {
      id: 'r-ex-7',
      section: 'extra',
      kind: 'choice',
      prompt: 'Số nào không phải là cách viết hợp lệ của một số hữu tỉ?',
      answer: '3/0',
      hint: 'Mẫu số phải khác 0.',
      solution: '3/0 không xác định vì mẫu bằng 0.',
      unit: '',
      options: ['3/0', '-3/2', '0', '0,5'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Số nào không phải là cách viết hợp lệ của một số hữu tỉ?',
      difficulty: 'easy',
      workspace: 'medium',
    },
    {
      id: 'r-ex-8',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Viết -0,75 dưới dạng phân số tối giản.',
      answer: '-3/4',
      hint: 'Viết -75/100 rồi rút gọn.',
      solution: '-0,75 = -75/100 = -3/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Viết -0,75 dưới dạng phân số tối giản.',
      difficulty: 'easy',
      workspace: 'medium',
    },
    {
      id: 'r-ex-9',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tìm số đối của -7/5.',
      answer: '7/5',
      hint: 'Đổi dấu của số đã cho.',
      solution: '-7/5 + 7/5 = 0 nên số đối là 7/5.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Tìm số đối của -7/5.',
      difficulty: 'easy',
      workspace: 'medium',
    },
    {
      id: 'r-ex-10',
      section: 'extra',
      kind: 'choice',
      prompt: 'Số 0 là số hữu tỉ như thế nào?',
      answer: 'Không dương cũng không âm',
      hint: 'Xét vị trí của 0 trên trục số.',
      solution: '0 = 0/1 là số hữu tỉ, không dương cũng không âm.',
      unit: '',
      options: ['Dương', 'Âm', 'Không dương cũng không âm'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'foundation',
      skill: 'Số 0 là số hữu tỉ như thế nào?',
      difficulty: 'easy',
      workspace: 'medium',
    },
    {
      id: 'r-ex-11',
      section: 'extra',
      kind: 'choice',
      prompt: 'So sánh -5/6 và -3/4.',
      answer: '-5/6 < -3/4',
      hint: 'Quy đồng mẫu 12.',
      solution: '-5/6 = -10/12 < -9/12 = -3/4.',
      unit: '',
      options: ['-5/6 < -3/4', '-5/6 > -3/4', '-5/6 = -3/4'],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'So sánh -5/6 và -3/4.',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-12',
      section: 'extra',
      kind: 'fraction',
      prompt:
        'Chia đoạn từ -1 đến 0 thành 4 phần bằng nhau. Đi từ -1 sang phải một phần, em đến số nào?',
      answer: '-3/4',
      hint: 'Cộng 1/4 vào -1.',
      solution: '-1 + 1/4 = -4/4 + 1/4 = -3/4.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill:
        'Chia đoạn từ -1 đến 0 thành 4 phần bằng nhau. Đi từ -1 sang phải một phần, em đến số nào?',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-13',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính -2/3 + 1/4.',
      answer: '-5/12',
      hint: 'Quy đồng mẫu 12.',
      solution: '-8/12 + 3/12 = -5/12.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính -2/3 + 1/4.',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-14',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính 5/6 − (-1/3).',
      answer: '7/6',
      hint: 'Trừ số âm là cộng số đối.',
      solution: '5/6 + 1/3 = 5/6 + 2/6 = 7/6.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính 5/6 − (-1/3).',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-15',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính (-3/7) × (14/9).',
      answer: '-2/3',
      hint: 'Rút gọn 3 với 9 cho 3, 14 với 7 cho 7 trước khi nhân.',
      solution: '(-3/7) × (14/9) = (-~3~ × ~7~ × 2)/(~7~ × ~3~ × 3) = -2/3.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính (-3/7) × (14/9).',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-16',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính (-5/8) : (-15/4).',
      answer: '1/6',
      hint: 'Nhân -5/8 với -4/15, rồi rút gọn 5 với 15 và 4 với 8 trước khi nhân.',
      solution:
        '(-5/8) : (-15/4) = (-5/8) × (-4/15) = (~5~ × ~4~)/(~4~ × 2 × ~5~ × 3) = 1/6.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính (-5/8) ',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-17',
      section: 'extra',
      kind: 'number',
      prompt: 'Tính -1,2 + 0,45.',
      answer: '-0.75',
      hint: 'Tính 1,20 − 0,45 rồi xét dấu.',
      solution: '-1,2 + 0,45 = -0,75.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính -1,2 + 0,45.',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-18',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính 1/2 + (-3/4) × (2/3).',
      answer: '0/1',
      hint: 'Thực hiện phép nhân trước.',
      solution:
        '1/2 + (-3/4) × (2/3) = 1/2 + (-~3~ × ~2~)/(2 × ~2~ × ~3~) = 1/2 − 1/2 = 0.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'skills',
      skill: 'Tính 1/2 + (-3/4) × (2/3).',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-19',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tìm x: x + 2/5 = -1/10.',
      answer: '-1/2',
      hint: 'Trừ 2/5 ở cả hai vế.',
      solution: 'x = -1/10 − 2/5 = -1/10 − 4/10 = -5/10 = -1/2.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Tìm x',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-20',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tìm x: x × (-3/4) = 1/2.',
      answer: '-2/3',
      hint: 'Chia hai vế cho -3/4.',
      solution:
        'x = (1/2) : (-3/4) = (1/2) × (-4/3) = (-~2~ × 2)/(~2~ × 3) = -2/3.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: 'Tìm x',
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-21',
      section: 'extra',
      kind: 'number',
      ...builtInExercisePrompts.rationalTemperature,
      answer: '1.25',
      hint: 'Tăng nhiệt độ nghĩa là cộng.',
      solution: '-2,5 + 3,75 = 1,25 °C.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: builtInExercisePrompts.rationalTemperature.prompt,
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-22',
      section: 'extra',
      kind: 'fraction',
      ...builtInExercisePrompts.rationalWater,
      answer: '7/12',
      hint: 'Lấy lượng ban đầu trừ lượng rót ra, cộng lượng thêm vào.',
      solution: '3/4 − 1/3 + 1/6 = 9/12 − 4/12 + 2/12 = 7/12 lít.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: builtInExercisePrompts.rationalWater.prompt,
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-23',
      section: 'extra',
      kind: 'fraction',
      ...builtInExercisePrompts.rationalDistance,
      answer: '23/20',
      hint: 'Cộng hai quãng đường.',
      solution: '2/5 + 3/4 = 8/20 + 15/20 = 23/20 km.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: builtInExercisePrompts.rationalDistance.prompt,
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-24',
      section: 'extra',
      kind: 'number',
      ...builtInExercisePrompts.rationalMoney,
      answer: '107.5',
      hint: 'Lấy 150 trừ 62,5 rồi cộng 20.',
      solution: '150 − 62,5 + 20 = 107,5 nghìn đồng.',
      unit: '',
      options: [],
      simplified: false,
      tolerance: 0,
      mistakes: [],
      group: 'application',
      skill: builtInExercisePrompts.rationalMoney.prompt,
      difficulty: 'medium',
      workspace: 'medium',
    },
    {
      id: 'r-ex-25',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tính hợp lí: (-7/9) × (3/5) + (-7/9) × (2/5).',
      answer: '-7/9',
      hint: 'Đặt -7/9 làm thừa số chung.',
      solution: '(-7/9) × (3/5 + 2/5) = (-7/9) × 1 = -7/9.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'challenge',
      skill: 'Tính hợp lí',
      difficulty: 'hard',
      workspace: 'medium',
    },
    {
      id: 'r-ex-26',
      section: 'extra',
      kind: 'fraction',
      prompt: 'Tìm một số hữu tỉ nằm chính giữa -2/3 và -1/2 trên trục số.',
      answer: '-7/12',
      hint: 'Cộng hai số rồi chia tổng cho 2.',
      solution:
        '(-2/3 − 1/2) : 2 = (-7/6) : 2 = -7/12. Kiểm tra: -8/12 < -7/12 < -6/12.',
      unit: '',
      options: [],
      simplified: true,
      tolerance: 0,
      mistakes: [],
      group: 'challenge',
      skill: 'Tìm một số hữu tỉ nằm chính giữa -2/3 và -1/2 trên trục số.',
      difficulty: 'hard',
      workspace: 'medium',
    },
    ...rationalSetExercises,
  ],
};
